 build[
     base: /opt/build/repo/Frontend
     command: npm install && npm run build
     commandOrigin: config
    environment:
       - VITE_API_BASE_URL
    publish: /opt/build/repo/Frontend/dist
    publishOrigin: config
]
