/**
 * seedPharmacyRestock.js  (R7gz)
 *
 * Comprehensive restock layered on top of seedPharmacy.js. Adds ~220
 * commonly-used Indian formulary drugs across every therapeutic class
 * the original seed missed (antivirals, antifungals, anaesthesia,
 * hematology, emergency-trolley, expanded antibiotics / cardiac /
 * gastro / neuro / respiratory, modern antidiabetics, etc).
 *
 * Idempotent — skips drugs that already exist by `name`. Adds 1–2
 * fresh batches per newly-created drug so FEFO / dispense / indent
 * flows have something to chew on immediately. Also cleans the four
 * pre-existing test rows ("probe", "Test Paracetamol 500mg",
 * "Audit Test Drug", "RT-Test Diclofenac 50mg") if --clean-test
 * is passed.
 *
 * Run:
 *   node Backend/scripts/seedPharmacyRestock.js
 *   node Backend/scripts/seedPharmacyRestock.js --clean-test
 *   node Backend/scripts/seedPharmacyRestock.js --batches-only   (skip drug create)
 */
require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });
const connectDB = require("../config/db");

const Drug      = require("../models/Pharmacy/DrugModel");
const DrugBatch = require("../models/Pharmacy/DrugBatchModel");
const Supplier  = require("../models/Pharmacy/SupplierModel");

const args         = process.argv.slice(2);
const CLEAN_TEST   = args.includes("--clean-test");
const BATCHES_ONLY = args.includes("--batches-only");

const TEST_NAMES = [
  "probe", "Test Paracetamol 500mg", "Audit Test Drug", "RT-Test Diclofenac 50mg",
];

/* ────────────────────────────────────────────────────────────────
   RESTOCK CATALOGUE — by therapeutic class. Every row uses the
   same shape as seedPharmacy.js so the importer below can stay tiny.
   isHighAlert flagged per ISMP list (insulins, opioids, anticoag,
   neuromuscular blockers, concentrated electrolytes).
──────────────────────────────────────────────────────────────── */
const RESTOCK = [
  // ── Antibiotics (Penicillins, Cephalosporins, Macrolides, Quinolones,
  //     Aminoglycosides, Glycopeptides, Carbapenems, Anti-TB, etc.) ──
  { name: "Amoxicillin + Clavulanate 625mg", genericName: "Amoxicillin/Clavulanic Acid", brandName: "Augmentin",  manufacturer: "GSK",          form: "Tablet",    strength: "500/125mg", pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 28 },
  { name: "Amoxicillin + Clavulanate 1.2g Inj", genericName: "Amoxicillin/Clavulanic Acid", brandName: "Augmentin IV", manufacturer: "GSK",     form: "Injection", strength: "1.2g",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 165 },
  { name: "Ampicillin 500mg Inj",          genericName: "Ampicillin",                 brandName: "Roscillin",   manufacturer: "Ranbaxy",      form: "Injection", strength: "500mg",     pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 22 },
  { name: "Piperacillin + Tazobactam 4.5g Inj", genericName: "Piperacillin/Tazobactam", brandName: "Zosyn",      manufacturer: "Pfizer",       form: "Injection", strength: "4.5g",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 295 },
  { name: "Cefuroxime 500mg",              genericName: "Cefuroxime Axetil",          brandName: "Ceftum",      manufacturer: "GSK",          form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 38 },
  { name: "Cefoperazone + Sulbactam 1.5g Inj", genericName: "Cefoperazone/Sulbactam", brandName: "Magnex",     manufacturer: "Pfizer",       form: "Injection", strength: "1.5g",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 245 },
  { name: "Cefepime 1g Inj",               genericName: "Cefepime",                   brandName: "Maxipime",    manufacturer: "BMS",          form: "Injection", strength: "1g",        pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 285 },
  { name: "Meropenem 1g Inj",              genericName: "Meropenem",                  brandName: "Meronem",     manufacturer: "Pfizer",       form: "Injection", strength: "1g",        pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 380 },
  { name: "Imipenem + Cilastatin 500mg Inj", genericName: "Imipenem/Cilastatin",      brandName: "Tienam",      manufacturer: "MSD",          form: "Injection", strength: "500mg",     pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 425 },
  { name: "Ertapenem 1g Inj",              genericName: "Ertapenem",                  brandName: "Invanz",      manufacturer: "MSD",          form: "Injection", strength: "1g",        pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 1450 },
  { name: "Vancomycin 500mg Inj",          genericName: "Vancomycin HCl",             brandName: "Vancocin",    manufacturer: "Pfizer",       form: "Injection", strength: "500mg",     pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 320 },
  { name: "Teicoplanin 400mg Inj",         genericName: "Teicoplanin",                brandName: "Targocid",    manufacturer: "Sanofi",       form: "Injection", strength: "400mg",     pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 1850 },
  { name: "Linezolid 600mg",               genericName: "Linezolid",                  brandName: "Lizolid",     manufacturer: "Pfizer",       form: "Tablet",    strength: "600mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 215 },
  { name: "Colistin 1MIU Inj",             genericName: "Colistimethate Sodium",      brandName: "Walamycin",   manufacturer: "Cipla",        form: "Injection", strength: "1MIU",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 195 },
  { name: "Polymyxin B 5L Inj",            genericName: "Polymyxin B",                brandName: "Polypeb",     manufacturer: "Bharat Serum", form: "Injection", strength: "5 lac IU",  pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 215 },
  { name: "Tigecycline 50mg Inj",          genericName: "Tigecycline",                brandName: "Tygacil",     manufacturer: "Pfizer",       form: "Injection", strength: "50mg",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 1250 },
  { name: "Amikacin 500mg Inj",            genericName: "Amikacin Sulphate",          brandName: "Mikacin",     manufacturer: "Aristo",       form: "Injection", strength: "500mg",     pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 68 },
  { name: "Gentamicin 80mg Inj",           genericName: "Gentamicin Sulphate",        brandName: "Genticyn",    manufacturer: "Abbott",       form: "Injection", strength: "80mg",      pack: "Ampoule",       category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Tobramycin 80mg Inj",           genericName: "Tobramycin",                 brandName: "Tobacin",     manufacturer: "Cadila",       form: "Injection", strength: "80mg",      pack: "Vial",          category: "Antibiotic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 95 },
  { name: "Clindamycin 300mg",             genericName: "Clindamycin HCl",            brandName: "Dalacin",     manufacturer: "Pfizer",       form: "Capsule",   strength: "300mg",     pack: "10 caps/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 32 },
  { name: "Clarithromycin 500mg",          genericName: "Clarithromycin",             brandName: "Clarid",      manufacturer: "Sun Pharma",   form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 48 },
  { name: "Faropenem 200mg",               genericName: "Faropenem Sodium",           brandName: "Farobact",    manufacturer: "Aristo",       form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 72 },
  { name: "Nitrofurantoin 100mg",          genericName: "Nitrofurantoin",             brandName: "Niftran",     manufacturer: "Cipla",        form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 14 },
  { name: "Trimethoprim + Sulfamethoxazole DS", genericName: "Co-trimoxazole",         brandName: "Septran DS",  manufacturer: "Abbott",       form: "Tablet",    strength: "800/160mg", pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 8 },
  { name: "Rifampicin 600mg",              genericName: "Rifampicin",                 brandName: "Rimactane",   manufacturer: "Lupin",        form: "Capsule",   strength: "600mg",     pack: "10 caps/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 22 },
  { name: "Isoniazid 300mg",               genericName: "Isoniazid",                  brandName: "Isokin",      manufacturer: "Lupin",        form: "Tablet",    strength: "300mg",     pack: "10 tabs/strip", category: "Antibiotic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },

  // ── Antivirals ──────────────────────────────────────────────
  { name: "Acyclovir 400mg",               genericName: "Acyclovir",                  brandName: "Zovirax",     manufacturer: "GSK",          form: "Tablet",    strength: "400mg",     pack: "10 tabs/strip", category: "Antiviral",  schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },
  { name: "Acyclovir 250mg Inj",           genericName: "Acyclovir Sodium",           brandName: "Zovirax IV",  manufacturer: "GSK",          form: "Injection", strength: "250mg",     pack: "Vial",          category: "Antiviral",  schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 220 },
  { name: "Valacyclovir 500mg",            genericName: "Valacyclovir",               brandName: "Valtrex",     manufacturer: "GSK",          form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Antiviral",  schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Oseltamivir 75mg",              genericName: "Oseltamivir Phosphate",      brandName: "Tamiflu",     manufacturer: "Roche",        form: "Capsule",   strength: "75mg",      pack: "10 caps/strip", category: "Antiviral",  schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 65 },
  { name: "Remdesivir 100mg Inj",          genericName: "Remdesivir",                 brandName: "CoviFor",     manufacturer: "Hetero",       form: "Injection", strength: "100mg",     pack: "Vial",          category: "Antiviral",  schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 2450, requiresRefrigeration: true },
  { name: "Tenofovir + Lamivudine + Dolutegravir", genericName: "TLD",                 brandName: "TLD",         manufacturer: "Mylan",        form: "Tablet",    strength: "300/300/50mg", pack: "30 tabs",    category: "Antiviral",  schedule: "H",  hsnCode: "30049099", gstRate: 5,  reorderLevel: 20,  defaultSalePrice: 320 },
  { name: "Sofosbuvir + Velpatasvir",      genericName: "Sofosbuvir/Velpatasvir",     brandName: "MyHep All",   manufacturer: "Mylan",        form: "Tablet",    strength: "400/100mg", pack: "28 tabs",       category: "Antiviral",  schedule: "H",  hsnCode: "30049099", gstRate: 5,  reorderLevel: 10,  defaultSalePrice: 1850 },

  // ── Antifungals ─────────────────────────────────────────────
  { name: "Fluconazole 150mg",             genericName: "Fluconazole",                brandName: "Forcan",      manufacturer: "Cipla",        form: "Capsule",   strength: "150mg",     pack: "1 cap",         category: "Antifungal", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 12 },
  { name: "Fluconazole 200mg Inj",         genericName: "Fluconazole",                brandName: "Forcan IV",   manufacturer: "Cipla",        form: "Injection", strength: "200mg/100mL", pack: "Bottle",      category: "Antifungal", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Itraconazole 100mg",            genericName: "Itraconazole",               brandName: "Itaspor",     manufacturer: "Cipla",        form: "Capsule",   strength: "100mg",     pack: "10 caps/strip", category: "Antifungal", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 28 },
  { name: "Voriconazole 200mg",            genericName: "Voriconazole",               brandName: "Vfend",       manufacturer: "Pfizer",       form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Antifungal", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 285 },
  { name: "Voriconazole 200mg Inj",        genericName: "Voriconazole",               brandName: "Vfend IV",    manufacturer: "Pfizer",       form: "Injection", strength: "200mg",     pack: "Vial",          category: "Antifungal", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 2150 },
  { name: "Amphotericin B Liposomal 50mg Inj", genericName: "Amphotericin B Liposomal", brandName: "Ambisome",  manufacturer: "Gilead",       form: "Injection", strength: "50mg",      pack: "Vial",          category: "Antifungal", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 10,  defaultSalePrice: 3950, requiresRefrigeration: true },
  { name: "Caspofungin 50mg Inj",          genericName: "Caspofungin",                brandName: "Cancidas",    manufacturer: "MSD",          form: "Injection", strength: "50mg",      pack: "Vial",          category: "Antifungal", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 10,  defaultSalePrice: 4250, requiresRefrigeration: true },
  { name: "Terbinafine 250mg",             genericName: "Terbinafine HCl",            brandName: "Lamisil",     manufacturer: "Novartis",     form: "Tablet",    strength: "250mg",     pack: "7 tabs/strip",  category: "Antifungal", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 32 },
  { name: "Clotrimazole 1% Cream",         genericName: "Clotrimazole",               brandName: "Candid",      manufacturer: "Glenmark",     form: "Cream",     strength: "1%",        pack: "20g tube",      category: "Antifungal", schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 85 },

  // ── Antiparasitic ───────────────────────────────────────────
  { name: "Albendazole 400mg",             genericName: "Albendazole",                brandName: "Zentel",      manufacturer: "GSK",          form: "Tablet",    strength: "400mg",     pack: "1 tab",         category: "Antiparasitic", schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 18 },
  { name: "Ivermectin 12mg",               genericName: "Ivermectin",                 brandName: "Iverwin",     manufacturer: "Wintech",      form: "Tablet",    strength: "12mg",      pack: "1 tab",         category: "Antiparasitic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Artemether + Lumefantrine",     genericName: "Artemether/Lumefantrine",    brandName: "Coartem",     manufacturer: "Novartis",     form: "Tablet",    strength: "80/480mg",  pack: "6 tabs",        category: "Antiparasitic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Chloroquine 250mg",             genericName: "Chloroquine Phosphate",      brandName: "Resochin",    manufacturer: "Bayer",        form: "Tablet",    strength: "250mg",     pack: "10 tabs/strip", category: "Antiparasitic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 6 },
  { name: "Hydroxychloroquine 200mg",      genericName: "Hydroxychloroquine Sulphate",brandName: "HCQS",        manufacturer: "IPCA",         form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Antiparasitic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },
  { name: "Praziquantel 600mg",            genericName: "Praziquantel",               brandName: "Distocide",   manufacturer: "Cipla",        form: "Tablet",    strength: "600mg",     pack: "4 tabs",        category: "Antiparasitic", schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 65 },

  // ── Analgesics / NSAIDs (incl PCM combos, opioids) ─────────
  { name: "Tramadol + Paracetamol",        genericName: "Tramadol/Paracetamol",       brandName: "Ultracet",    manufacturer: "Janssen",      form: "Tablet",    strength: "37.5/325mg", pack: "10 tabs/strip", category: "Analgesic", schedule: "H1", hsnCode: "30049011", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 12, isNarcotic: true },
  { name: "Paracetamol 1g Inj",            genericName: "Paracetamol",                brandName: "Perfalgan",   manufacturer: "BMS",          form: "Injection", strength: "1g/100mL",  pack: "Bottle",        category: "Analgesic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 78 },
  { name: "Diclofenac 75mg Inj",           genericName: "Diclofenac Sodium",          brandName: "Voveran",     manufacturer: "Novartis",     form: "Injection", strength: "75mg/3mL",  pack: "Ampoule",       category: "Analgesic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 100, defaultSalePrice: 8 },
  { name: "Ketorolac 30mg Inj",            genericName: "Ketorolac Tromethamine",     brandName: "Ketanov",     manufacturer: "Pharmacia",    form: "Injection", strength: "30mg/1mL",  pack: "Ampoule",       category: "Analgesic", schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },
  { name: "Etoricoxib 90mg",               genericName: "Etoricoxib",                 brandName: "Etody",       manufacturer: "Zydus",        form: "Tablet",    strength: "90mg",      pack: "10 tabs/strip", category: "Analgesic", schedule: "H",  hsnCode: "30049011", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 18 },
  { name: "Naproxen 500mg",                genericName: "Naproxen Sodium",            brandName: "Naprosyn",    manufacturer: "Themis",       form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Analgesic", schedule: "H",  hsnCode: "30049011", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 14 },
  { name: "Mefenamic Acid 500mg",          genericName: "Mefenamic Acid",             brandName: "Meftal",      manufacturer: "Blue Cross",   form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Analgesic", schedule: "H",  hsnCode: "30049011", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 6 },
  { name: "Fentanyl 100mcg Inj",           genericName: "Fentanyl Citrate",           brandName: "Trofentyl",   manufacturer: "Troikaa",      form: "Injection", strength: "100mcg/2mL",pack: "Ampoule",       category: "Analgesic", schedule: "X",  hsnCode: "30042020", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 28, isHighAlert: true, isNarcotic: true },
  { name: "Pethidine 100mg Inj",           genericName: "Pethidine HCl",              brandName: "Pethidine",   manufacturer: "Neon",         form: "Injection", strength: "100mg/2mL", pack: "Ampoule",       category: "Analgesic", schedule: "X",  hsnCode: "30042020", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 24, isHighAlert: true, isNarcotic: true },
  { name: "Buprenorphine 0.3mg Inj",       genericName: "Buprenorphine HCl",          brandName: "Norphin",     manufacturer: "Sun Pharma",   form: "Injection", strength: "0.3mg/1mL", pack: "Ampoule",       category: "Analgesic", schedule: "X",  hsnCode: "30042020", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 32, isHighAlert: true, isNarcotic: true },

  // ── Antihypertensives (expanded — Diuretics, more ACEi/ARB/CCB/BB) ──
  { name: "Furosemide 40mg",               genericName: "Furosemide",                 brandName: "Lasix",       manufacturer: "Sanofi",       form: "Tablet",    strength: "40mg",      pack: "15 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 120, defaultSalePrice: 3 },
  { name: "Furosemide 20mg Inj",           genericName: "Furosemide",                 brandName: "Lasix",       manufacturer: "Sanofi",       form: "Injection", strength: "20mg/2mL",  pack: "Ampoule",       category: "Antihypertensive", schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 8 },
  { name: "Torsemide 10mg",                genericName: "Torsemide",                  brandName: "Dytor",       manufacturer: "Cipla",        form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 12 },
  { name: "Spironolactone 25mg",           genericName: "Spironolactone",             brandName: "Aldactone",   manufacturer: "RPG",          form: "Tablet",    strength: "25mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 8 },
  { name: "Hydrochlorothiazide 12.5mg",    genericName: "Hydrochlorothiazide",        brandName: "Aquazide",    manufacturer: "Sun Pharma",   form: "Tablet",    strength: "12.5mg",    pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Amlodipine + Olmesartan",       genericName: "Amlodipine/Olmesartan",      brandName: "Olmesar A",   manufacturer: "Macleods",     form: "Tablet",    strength: "5/20mg",    pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },
  { name: "Bisoprolol 5mg",                genericName: "Bisoprolol Fumarate",        brandName: "Concor",      manufacturer: "Merck",        form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 14 },
  { name: "Carvedilol 6.25mg",             genericName: "Carvedilol",                 brandName: "Cardivas",    manufacturer: "Sun Pharma",   form: "Tablet",    strength: "6.25mg",    pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 9 },
  { name: "Nebivolol 5mg",                 genericName: "Nebivolol",                  brandName: "Nebicard",    manufacturer: "Torrent",      form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 18 },
  { name: "Labetalol 100mg",               genericName: "Labetalol HCl",              brandName: "Lobet",       manufacturer: "Sun Pharma",   form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Labetalol 20mg Inj",            genericName: "Labetalol HCl",              brandName: "Lobet IV",    manufacturer: "Sun Pharma",   form: "Injection", strength: "20mg/4mL",  pack: "Ampoule",       category: "Antihypertensive", schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 65 },
  { name: "Enalapril 5mg",                 genericName: "Enalapril Maleate",          brandName: "Envas",       manufacturer: "Cadila",       form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 7 },
  { name: "Lisinopril 5mg",                genericName: "Lisinopril",                 brandName: "Lipril",      manufacturer: "Lupin",        form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 9 },
  { name: "Olmesartan 20mg",               genericName: "Olmesartan Medoxomil",       brandName: "Olmezest",    manufacturer: "Macleods",     form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Valsartan 80mg",                genericName: "Valsartan",                  brandName: "Diovan",      manufacturer: "Novartis",     form: "Tablet",    strength: "80mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 14 },
  { name: "Cilnidipine 10mg",              genericName: "Cilnidipine",                brandName: "Cilacar",     manufacturer: "JB Chemicals", form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Nifedipine Retard 20mg",        genericName: "Nifedipine",                 brandName: "Depin",       manufacturer: "Wockhardt",    form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 8 },
  { name: "Clonidine 0.1mg",               genericName: "Clonidine HCl",              brandName: "Catapres",    manufacturer: "Boehringer",   form: "Tablet",    strength: "0.1mg",     pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 6 },
  { name: "Prazosin 2.5mg",                genericName: "Prazosin HCl",               brandName: "Minipress XL",manufacturer: "Pfizer",       form: "Tablet",    strength: "2.5mg",     pack: "10 tabs/strip", category: "Antihypertensive", schedule: "H", hsnCode: "30049022", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 22 },

  // ── Antidiabetics (modern — SGLT2, GLP1, gliptins, premixed) ──
  { name: "Glipizide 5mg",                 genericName: "Glipizide",                  brandName: "Glytop",      manufacturer: "Sun Pharma",   form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 8 },
  { name: "Gliclazide MR 60mg",            genericName: "Gliclazide",                 brandName: "Diamicron MR",manufacturer: "Serdia",       form: "Tablet",    strength: "60mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 14 },
  { name: "Vildagliptin 50mg",             genericName: "Vildagliptin",               brandName: "Galvus",      manufacturer: "Novartis",     form: "Tablet",    strength: "50mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 32 },
  { name: "Linagliptin 5mg",               genericName: "Linagliptin",                brandName: "Trajenta",    manufacturer: "Boehringer",   form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 48 },
  { name: "Teneligliptin 20mg",            genericName: "Teneligliptin",              brandName: "Zita",        manufacturer: "Glenmark",     form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 18 },
  { name: "Dapagliflozin 10mg",            genericName: "Dapagliflozin",              brandName: "Forxiga",     manufacturer: "AstraZeneca",  form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 56 },
  { name: "Empagliflozin 10mg",            genericName: "Empagliflozin",              brandName: "Jardiance",   manufacturer: "Boehringer",   form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 64 },
  { name: "Canagliflozin 100mg",           genericName: "Canagliflozin",              brandName: "Invokana",    manufacturer: "Janssen",      form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 78 },
  { name: "Liraglutide 6mg/mL Inj",        genericName: "Liraglutide",                brandName: "Victoza",     manufacturer: "Novo Nordisk", form: "Injection", strength: "6mg/mL",    pack: "3mL pen",       category: "Antidiabetic", schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 15,  defaultSalePrice: 1850, isHighAlert: true, requiresRefrigeration: true },
  { name: "Semaglutide 0.25mg Inj",        genericName: "Semaglutide",                brandName: "Ozempic",     manufacturer: "Novo Nordisk", form: "Injection", strength: "0.25mg/dose",pack: "1.5mL pen",     category: "Antidiabetic", schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 10,  defaultSalePrice: 4250, isHighAlert: true, requiresRefrigeration: true },
  { name: "Pioglitazone 15mg",             genericName: "Pioglitazone",               brandName: "Pioz",        manufacturer: "USV",          form: "Tablet",    strength: "15mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 12 },
  { name: "Voglibose 0.3mg",               genericName: "Voglibose",                  brandName: "Vocarb",      manufacturer: "Glenmark",     form: "Tablet",    strength: "0.3mg",     pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 8 },
  { name: "Acarbose 50mg",                 genericName: "Acarbose",                   brandName: "Glucobay",    manufacturer: "Bayer",        form: "Tablet",    strength: "50mg",      pack: "10 tabs/strip", category: "Antidiabetic", schedule: "H", hsnCode: "30049030", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 14 },
  { name: "Insulin NPH (Insulatard)",      genericName: "Isophane Insulin",           brandName: "Insulatard",  manufacturer: "Novo Nordisk", form: "Injection", strength: "100 IU/mL", pack: "3mL cartridge", category: "Insulin",      schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 25,  defaultSalePrice: 415, isHighAlert: true, requiresRefrigeration: true },
  { name: "Insulin Aspart (NovoRapid)",    genericName: "Insulin Aspart",             brandName: "NovoRapid",   manufacturer: "Novo Nordisk", form: "Injection", strength: "100 IU/mL", pack: "3mL cartridge", category: "Insulin",      schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 25,  defaultSalePrice: 615, isHighAlert: true, requiresRefrigeration: true },
  { name: "Insulin Detemir (Levemir)",     genericName: "Insulin Detemir",            brandName: "Levemir",     manufacturer: "Novo Nordisk", form: "Injection", strength: "100 IU/mL", pack: "3mL cartridge", category: "Insulin",      schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 20,  defaultSalePrice: 815, isHighAlert: true, requiresRefrigeration: true },
  { name: "Premixed 70/30 (Mixtard)",      genericName: "Biphasic Human Insulin",     brandName: "Mixtard 30/70",manufacturer:"Novo Nordisk", form: "Injection", strength: "100 IU/mL", pack: "3mL cartridge", category: "Insulin",      schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 30,  defaultSalePrice: 215, isHighAlert: true, requiresRefrigeration: true },
  { name: "Insulin Degludec (Tresiba)",    genericName: "Insulin Degludec",           brandName: "Tresiba",     manufacturer: "Novo Nordisk", form: "Injection", strength: "100 IU/mL", pack: "3mL pen",       category: "Insulin",      schedule: "H", hsnCode: "30043910", gstRate: 5,  reorderLevel: 15,  defaultSalePrice: 1850, isHighAlert: true, requiresRefrigeration: true },

  // ── Cardiac (expanded — DOACs, antiplatelet, antiarrhythmic, vasodilators) ──
  { name: "Apixaban 5mg",                  genericName: "Apixaban",                   brandName: "Eliquis",     manufacturer: "BMS",          form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Hematology",   schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 38, isHighAlert: true },
  { name: "Rivaroxaban 15mg",              genericName: "Rivaroxaban",                brandName: "Xarelto",     manufacturer: "Bayer",        form: "Tablet",    strength: "15mg",      pack: "10 tabs/strip", category: "Hematology",   schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 56, isHighAlert: true },
  { name: "Dabigatran 110mg",              genericName: "Dabigatran Etexilate",       brandName: "Pradaxa",     manufacturer: "Boehringer",   form: "Capsule",   strength: "110mg",     pack: "10 caps/strip", category: "Hematology",   schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 78, isHighAlert: true },
  { name: "Enoxaparin 40mg Inj",           genericName: "Enoxaparin Sodium",          brandName: "Clexane",     manufacturer: "Sanofi",       form: "Injection", strength: "40mg/0.4mL",pack: "PFS",           category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 285, isHighAlert: true, requiresRefrigeration: true },
  { name: "Enoxaparin 60mg Inj",           genericName: "Enoxaparin Sodium",          brandName: "Clexane",     manufacturer: "Sanofi",       form: "Injection", strength: "60mg/0.6mL",pack: "PFS",           category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 385, isHighAlert: true, requiresRefrigeration: true },
  { name: "Heparin 5000IU Inj",            genericName: "Heparin Sodium",             brandName: "Heparin",     manufacturer: "Beparine",     form: "Injection", strength: "5000 IU/mL",pack: "5mL vial",      category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 115, isHighAlert: true },
  { name: "Acenocoumarol 2mg",             genericName: "Acenocoumarol",              brandName: "Acitrom",     manufacturer: "Abbott",       form: "Tablet",    strength: "2mg",       pack: "10 tabs/strip", category: "Hematology",   schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18, isHighAlert: true },
  { name: "Ticagrelor 90mg",               genericName: "Ticagrelor",                 brandName: "Brilinta",    manufacturer: "AstraZeneca",  form: "Tablet",    strength: "90mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 35 },
  { name: "Prasugrel 10mg",                genericName: "Prasugrel",                  brandName: "Effient",     manufacturer: "Lilly",        form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 42 },
  { name: "Tranexamic Acid 500mg Inj",     genericName: "Tranexamic Acid",            brandName: "Cyklokapron", manufacturer: "Pfizer",       form: "Injection", strength: "500mg/5mL", pack: "Ampoule",       category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 32 },
  { name: "Vitamin K 10mg Inj",            genericName: "Phytomenadione",             brandName: "Kapilin",     manufacturer: "Macleods",     form: "Injection", strength: "10mg/1mL",  pack: "Ampoule",       category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Erythropoietin 4000IU Inj",     genericName: "Recombinant Human EPO",      brandName: "Eprex",       manufacturer: "Janssen",      form: "Injection", strength: "4000 IU",   pack: "PFS",           category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 425, requiresRefrigeration: true },
  { name: "Iron Sucrose 100mg Inj",        genericName: "Iron Sucrose",               brandName: "Venofer",     manufacturer: "Emcure",       form: "Injection", strength: "100mg/5mL", pack: "Ampoule",       category: "Hematology",   schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 165 },
  { name: "Amiodarone 200mg",              genericName: "Amiodarone HCl",             brandName: "Cordarone",   manufacturer: "Sanofi",       form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 22 },
  { name: "Amiodarone 150mg Inj",          genericName: "Amiodarone HCl",             brandName: "Cordarone",   manufacturer: "Sanofi",       form: "Injection", strength: "150mg/3mL", pack: "Ampoule",       category: "Cardiac",      schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 145, isHighAlert: true },
  { name: "Digoxin 0.25mg",                genericName: "Digoxin",                    brandName: "Lanoxin",     manufacturer: "GSK",          form: "Tablet",    strength: "0.25mg",    pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 6, isHighAlert: true },
  { name: "Ivabradine 5mg",                genericName: "Ivabradine",                 brandName: "Ivabrad",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 28 },
  { name: "Sacubitril + Valsartan",        genericName: "Sacubitril/Valsartan",       brandName: "Vymada",      manufacturer: "Novartis",     form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 78 },
  { name: "Isosorbide Mononitrate 20mg",   genericName: "ISMN",                       brandName: "Monotrate",   manufacturer: "Sun Pharma",   form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 8 },
  { name: "Isosorbide Dinitrate 10mg",     genericName: "ISDN",                       brandName: "Sorbitrate",  manufacturer: "Abbott",       form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Adenosine 6mg Inj",             genericName: "Adenosine",                  brandName: "Adenoject",   manufacturer: "Sun Pharma",   form: "Injection", strength: "6mg/2mL",   pack: "Ampoule",       category: "Cardiac",      schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 125, isHighAlert: true },
  { name: "Atorvastatin 40mg",             genericName: "Atorvastatin",               brandName: "Atorva",      manufacturer: "Zydus",        form: "Tablet",    strength: "40mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 14 },
  { name: "Ezetimibe 10mg",                genericName: "Ezetimibe",                  brandName: "Ezetib",      manufacturer: "MSN",          form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 22 },
  { name: "Fenofibrate 160mg",             genericName: "Fenofibrate",                brandName: "Lipicard",    manufacturer: "USV",          form: "Tablet",    strength: "160mg",     pack: "10 tabs/strip", category: "Cardiac",      schedule: "H", hsnCode: "30049029", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },

  // ── Respiratory (expanded — ICS, LABA, LAMA combos, antihistamines, expectorants) ──
  { name: "Salmeterol + Fluticasone 25/250 Inhaler", genericName: "Salmeterol/Fluticasone", brandName: "Seretide", manufacturer: "GSK",      form: "Inhaler",   strength: "25/250mcg", pack: "120 doses",     category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 685 },
  { name: "Formoterol + Budesonide 6/200 Inhaler", genericName: "Formoterol/Budesonide", brandName: "Symbicort",  manufacturer: "AstraZeneca", form: "Inhaler", strength: "6/200mcg",   pack: "120 doses",     category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 615 },
  { name: "Tiotropium 18mcg Inhaler",      genericName: "Tiotropium Bromide",         brandName: "Spiriva",     manufacturer: "Boehringer",   form: "Inhaler",   strength: "18mcg",     pack: "30 caps",       category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 425 },
  { name: "Ipratropium + Salbutamol Resp Sol", genericName: "Ipratropium/Salbutamol", brandName: "Duolin",      manufacturer: "Cipla",        form: "Drops",     strength: "0.5/2.5mg", pack: "30 respules",   category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 145 },
  { name: "Levosalbutamol Resp Sol",       genericName: "Levosalbutamol",             brandName: "Levolin",     manufacturer: "Cipla",        form: "Drops",     strength: "1.25mg/2.5mL", pack: "30 respules", category: "Respiratory", schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Budesonide Respules",           genericName: "Budesonide",                 brandName: "Budecort",    manufacturer: "Cipla",        form: "Drops",     strength: "0.5mg/2mL", pack: "5 respules",    category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 85 },
  { name: "Theophylline SR 200mg",         genericName: "Theophylline",               brandName: "Theo-Asthalin",manufacturer:"Cipla",        form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 9 },
  { name: "Doxofylline 400mg",             genericName: "Doxofylline",                brandName: "Doxiflo",     manufacturer: "Aristo",       form: "Tablet",    strength: "400mg",     pack: "10 tabs/strip", category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Aminophylline 250mg Inj",       genericName: "Aminophylline",              brandName: "Aminophylline",manufacturer:"Neon",         form: "Injection", strength: "250mg/10mL",pack: "Ampoule",       category: "Respiratory",  schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 12 },
  { name: "Levocetirizine 5mg",            genericName: "Levocetirizine HCl",         brandName: "Vozet",       manufacturer: "Glenmark",     form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Respiratory",  schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 6 },
  { name: "Fexofenadine 120mg",            genericName: "Fexofenadine",               brandName: "Allegra",     manufacturer: "Sanofi",       form: "Tablet",    strength: "120mg",     pack: "10 tabs/strip", category: "Respiratory",  schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 14 },
  { name: "Chlorpheniramine 4mg",          genericName: "Chlorpheniramine Maleate",   brandName: "Avil",        manufacturer: "Sanofi",       form: "Tablet",    strength: "4mg",       pack: "10 tabs/strip", category: "Respiratory",  schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 3 },
  { name: "Pheniramine 22.75mg Inj",       genericName: "Pheniramine Maleate",        brandName: "Avil IV",     manufacturer: "Sanofi",       form: "Injection", strength: "22.75mg/1mL",pack: "Ampoule",      category: "Respiratory",  schedule: "H", hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 9 },
  { name: "Ambroxol 30mg",                 genericName: "Ambroxol HCl",               brandName: "Mucolite",    manufacturer: "Glenmark",     form: "Tablet",    strength: "30mg",      pack: "10 tabs/strip", category: "Respiratory",  schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Acetylcysteine 600mg",          genericName: "N-Acetylcysteine",           brandName: "Mucinac",     manufacturer: "Cipla",        form: "Tablet",    strength: "600mg",     pack: "10 tabs/strip", category: "Respiratory",  schedule: "H", hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 22 },

  // ── Gastro (expanded — H2 blockers, antacids, antiemetics, antispasmodics, laxatives, probiotics, hepatoprotective) ──
  { name: "Esomeprazole 40mg",             genericName: "Esomeprazole",               brandName: "Nexpro",      manufacturer: "Sun Pharma",   form: "Tablet",    strength: "40mg",      pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 12 },
  { name: "Rabeprazole 20mg",              genericName: "Rabeprazole Sodium",         brandName: "Rabicip",     manufacturer: "Cipla",        form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 9 },
  { name: "Lansoprazole 30mg",             genericName: "Lansoprazole",               brandName: "Lanzol",      manufacturer: "Cipla",        form: "Capsule",   strength: "30mg",      pack: "10 caps/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 7 },
  { name: "Pantoprazole 40mg Inj",         genericName: "Pantoprazole",               brandName: "Pantop IV",   manufacturer: "Sun Pharma",   form: "Injection", strength: "40mg",      pack: "Vial",          category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 28 },
  { name: "Ranitidine 150mg",              genericName: "Ranitidine",                 brandName: "Zinetac",     manufacturer: "GSK",          form: "Tablet",    strength: "150mg",     pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 4 },
  { name: "Famotidine 20mg",               genericName: "Famotidine",                 brandName: "Famocid",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 6 },
  { name: "Sucralfate Suspension",         genericName: "Sucralfate",                 brandName: "Sucrafil",    manufacturer: "Macleods",     form: "Syrup",     strength: "1g/10mL",   pack: "200mL bottle",  category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Magnesium Hydroxide + Al Hydroxide Syp", genericName: "Antacid Susp",      brandName: "Digene",      manufacturer: "Abbott",       form: "Syrup",     strength: "200/200mg/5mL",pack:"170mL",       category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Ondansetron 4mg Inj",           genericName: "Ondansetron",                brandName: "Emeset",      manufacturer: "Cipla",        form: "Injection", strength: "4mg/2mL",   pack: "Ampoule",       category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 9 },
  { name: "Metoclopramide 10mg Inj",       genericName: "Metoclopramide HCl",         brandName: "Perinorm",    manufacturer: "Ipca",         form: "Injection", strength: "10mg/2mL",  pack: "Ampoule",       category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Granisetron 1mg Inj",           genericName: "Granisetron HCl",            brandName: "Granicip",    manufacturer: "Cipla",        form: "Injection", strength: "1mg/1mL",   pack: "Ampoule",       category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 95 },
  { name: "Hyoscine Butylbromide 20mg Inj",genericName: "Hyoscine N-Butyl Bromide",   brandName: "Buscopan",    manufacturer: "Boehringer",   form: "Injection", strength: "20mg/1mL",  pack: "Ampoule",       category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Drotaverine 40mg",              genericName: "Drotaverine HCl",            brandName: "Drotin",      manufacturer: "Walter Bushnell",form:"Tablet",   strength: "40mg",      pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 8 },
  { name: "Dicyclomine 20mg",              genericName: "Dicyclomine HCl",            brandName: "Cyclopam",    manufacturer: "Indoco",       form: "Tablet",    strength: "20mg",      pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Lactulose Syrup",               genericName: "Lactulose",                  brandName: "Duphalac",    manufacturer: "Abbott",       form: "Syrup",     strength: "10g/15mL",  pack: "200mL bottle",  category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 165 },
  { name: "Bisacodyl 5mg",                 genericName: "Bisacodyl",                  brandName: "Dulcolax",    manufacturer: "Boehringer",   form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 6 },
  { name: "Polyethylene Glycol Sachet",    genericName: "PEG 3350",                   brandName: "Peglec",      manufacturer: "Tablets India",form: "Powder",    strength: "137g",      pack: "Sachet",        category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 125 },
  { name: "Saccharomyces boulardii",       genericName: "S. boulardii",               brandName: "Econorm",     manufacturer: "Dr. Reddy's",  form: "Powder",    strength: "250mg",     pack: "Sachet",        category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 22 },
  { name: "ORS Powder",                    genericName: "Oral Rehydration Salts",     brandName: "ORS",         manufacturer: "FDC",          form: "Powder",    strength: "WHO formula",pack: "Sachet 21g",   category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 5,  reorderLevel: 200, defaultSalePrice: 18 },
  { name: "Mesalamine 800mg",              genericName: "Mesalazine",                 brandName: "Mesacol",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "800mg",     pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 65 },
  { name: "Ursodeoxycholic Acid 300mg",    genericName: "UDCA",                       brandName: "Udiliv",      manufacturer: "Abbott",       form: "Tablet",    strength: "300mg",     pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 56 },
  { name: "L-Ornithine L-Aspartate Inj",   genericName: "L-Ornithine L-Aspartate",    brandName: "Hepamerz",    manufacturer: "Sanofi",       form: "Injection", strength: "5g/10mL",   pack: "Ampoule",       category: "Gastro",       schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 285 },
  { name: "Silymarin 140mg",               genericName: "Silymarin",                  brandName: "Silybon",     manufacturer: "Micro Labs",   form: "Tablet",    strength: "140mg",     pack: "10 tabs/strip", category: "Gastro",       schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },

  // ── Neuro (expanded — antiepileptics, antidepressants, antipsychotics, anxiolytics, antiparkinson) ──
  { name: "Phenobarbitone 60mg",           genericName: "Phenobarbital",              brandName: "Gardenal",    manufacturer: "Abbott",       form: "Tablet",    strength: "60mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H1", hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 5, isHighAlert: true },
  { name: "Carbamazepine 200mg",           genericName: "Carbamazepine",              brandName: "Tegretol",    manufacturer: "Novartis",     form: "Tablet",    strength: "200mg",     pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 8 },
  { name: "Valproate 500mg",               genericName: "Sodium Valproate",           brandName: "Valance OD",  manufacturer: "Sun Pharma",   form: "Tablet",    strength: "500mg",     pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 14 },
  { name: "Lacosamide 100mg",              genericName: "Lacosamide",                 brandName: "Lacosam",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 32 },
  { name: "Lamotrigine 50mg",              genericName: "Lamotrigine",                brandName: "Lamictal",    manufacturer: "GSK",          form: "Tablet",    strength: "50mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Topiramate 50mg",               genericName: "Topiramate",                 brandName: "Topamac",     manufacturer: "Janssen",      form: "Tablet",    strength: "50mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 28 },
  { name: "Pregabalin 75mg",               genericName: "Pregabalin",                 brandName: "Lyrica",      manufacturer: "Pfizer",       form: "Capsule",   strength: "75mg",      pack: "10 caps/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 22 },
  { name: "Sertraline 50mg",               genericName: "Sertraline HCl",             brandName: "Daxid",       manufacturer: "Sun Pharma",   form: "Tablet",    strength: "50mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 28 },
  { name: "Fluoxetine 20mg",               genericName: "Fluoxetine HCl",             brandName: "Fludac",      manufacturer: "Cadila",       form: "Capsule",   strength: "20mg",      pack: "10 caps/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 14 },
  { name: "Escitalopram 10mg",             genericName: "Escitalopram Oxalate",       brandName: "Nexito",      manufacturer: "Sun Pharma",   form: "Tablet",    strength: "10mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Duloxetine 30mg",               genericName: "Duloxetine HCl",             brandName: "Duvanta",     manufacturer: "Intas",        form: "Capsule",   strength: "30mg",      pack: "10 caps/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 22 },
  { name: "Amitriptyline 25mg",            genericName: "Amitriptyline HCl",          brandName: "Amitone",     manufacturer: "Intas",        form: "Tablet",    strength: "25mg",      pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 6 },
  { name: "Olanzapine 5mg",                genericName: "Olanzapine",                 brandName: "Oleanz",      manufacturer: "Sun Pharma",   form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 18 },
  { name: "Risperidone 2mg",               genericName: "Risperidone",                brandName: "Risdone",     manufacturer: "Torrent",      form: "Tablet",    strength: "2mg",       pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 14 },
  { name: "Haloperidol 5mg Inj",           genericName: "Haloperidol",                brandName: "Serenace",    manufacturer: "RPG",          form: "Injection", strength: "5mg/1mL",   pack: "Ampoule",       category: "Neuro",        schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 6 },
  { name: "Quetiapine 100mg",              genericName: "Quetiapine Fumarate",        brandName: "Qutipin",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "100mg",     pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 22 },
  { name: "Alprazolam 0.5mg",              genericName: "Alprazolam",                 brandName: "Alprax",      manufacturer: "Torrent",      form: "Tablet",    strength: "0.5mg",     pack: "10 tabs/strip", category: "Neuro",        schedule: "H1", hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 8, isHighAlert: true },
  { name: "Lorazepam 2mg",                 genericName: "Lorazepam",                  brandName: "Ativan",      manufacturer: "Pfizer",       form: "Tablet",    strength: "2mg",       pack: "10 tabs/strip", category: "Neuro",        schedule: "H1", hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 9, isHighAlert: true },
  { name: "Lorazepam 4mg Inj",             genericName: "Lorazepam",                  brandName: "Lorazepam",   manufacturer: "Neon",         form: "Injection", strength: "4mg/2mL",   pack: "Ampoule",       category: "Neuro",        schedule: "H1", hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 35, isHighAlert: true },
  { name: "Midazolam 5mg Inj",             genericName: "Midazolam",                  brandName: "Fulsed",      manufacturer: "Sun Pharma",   form: "Injection", strength: "5mg/5mL",   pack: "Ampoule",       category: "Anesthesia",   schedule: "H1", hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18, isHighAlert: true, isNarcotic: true },
  { name: "Diazepam 10mg Inj",             genericName: "Diazepam",                   brandName: "Calmpose",    manufacturer: "Ranbaxy",      form: "Injection", strength: "10mg/2mL",  pack: "Ampoule",       category: "Neuro",        schedule: "H1", hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 9, isHighAlert: true },
  { name: "Levodopa + Carbidopa",          genericName: "Levodopa/Carbidopa",         brandName: "Syndopa",     manufacturer: "Sun Pharma",   form: "Tablet",    strength: "100/25mg",  pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 14 },
  { name: "Donepezil 5mg",                 genericName: "Donepezil HCl",              brandName: "Donep",       manufacturer: "Cipla",        form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Neuro",        schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 18 },
  { name: "Mannitol 20% Inj",              genericName: "Mannitol",                   brandName: "Mannitol",    manufacturer: "Claris",       form: "Injection", strength: "20% 100mL", pack: "Bottle",        category: "Neuro",        schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },

  // ── Steroids (expanded) ────────────────────────────────────
  { name: "Methylprednisolone 500mg Inj",  genericName: "Methylprednisolone",         brandName: "Solu-Medrol", manufacturer: "Pfizer",       form: "Injection", strength: "500mg",     pack: "Vial",          category: "Steroid",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 425 },
  { name: "Methylprednisolone 16mg",       genericName: "Methylprednisolone",         brandName: "Medrol",      manufacturer: "Pfizer",       form: "Tablet",    strength: "16mg",      pack: "10 tabs/strip", category: "Steroid",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 32 },
  { name: "Hydrocortisone 200mg Inj",      genericName: "Hydrocortisone Sodium Succinate", brandName: "Efcorlin",manufacturer: "Sun Pharma",   form: "Injection", strength: "200mg",   pack: "Vial",          category: "Steroid",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 65 },
  { name: "Prednisolone 5mg",              genericName: "Prednisolone",               brandName: "Wysolone",    manufacturer: "Wyeth",        form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Steroid",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 4 },
  { name: "Deflazacort 6mg",               genericName: "Deflazacort",                brandName: "Defcort",     manufacturer: "Macleods",     form: "Tablet",    strength: "6mg",       pack: "10 tabs/strip", category: "Steroid",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18 },
  { name: "Triamcinolone 40mg Inj",        genericName: "Triamcinolone Acetonide",    brandName: "Kenacort",    manufacturer: "Abbott",       form: "Injection", strength: "40mg/1mL",  pack: "Vial",          category: "Steroid",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 215 },
  { name: "Fluticasone Nasal Spray",       genericName: "Fluticasone Propionate",     brandName: "Flomist",     manufacturer: "Cipla",        form: "Drops",     strength: "50mcg/dose",pack: "120 doses",     category: "Steroid",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 285 },

  // ── Vitamins / Supplements (expanded) ──────────────────────
  { name: "Vitamin D3 60000 IU",           genericName: "Cholecalciferol",            brandName: "Calcirol",    manufacturer: "Cadila",       form: "Powder",    strength: "60000 IU",  pack: "Sachet 1g",     category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 32 },
  { name: "Calcium Carbonate + Vitamin D3",genericName: "Calcium/Vit D3",             brandName: "Shelcal 500", manufacturer: "Torrent",      form: "Tablet",    strength: "500mg/250IU",pack:"15 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 14 },
  { name: "Multivitamin Tablet",           genericName: "Multivitamin",               brandName: "Becosules",   manufacturer: "Pfizer",       form: "Capsule",   strength: "B-complex", pack: "20 caps/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 4 },
  { name: "Mecobalamin 500mcg",            genericName: "Mecobalamin",                brandName: "Methycobal",  manufacturer: "Eisai",        form: "Tablet",    strength: "500mcg",    pack: "10 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 12 },
  { name: "Mecobalamin 1500mcg Inj",       genericName: "Mecobalamin",                brandName: "Methycobal",  manufacturer: "Eisai",        form: "Injection", strength: "1500mcg/1mL",pack: "Ampoule",       category: "Vitamin",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Folic Acid 5mg",                genericName: "Folic Acid",                 brandName: "Folvite",     manufacturer: "Wyeth",        form: "Tablet",    strength: "5mg",       pack: "10 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 3 },
  { name: "Iron + Folic Acid",             genericName: "Ferrous Ascorbate/Folic Acid",brandName: "Autrin",     manufacturer: "Pfizer",       form: "Tablet",    strength: "100/1.1mg", pack: "10 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 100, defaultSalePrice: 8 },
  { name: "Thiamine 100mg Inj",            genericName: "Thiamine HCl",               brandName: "Beneural",    manufacturer: "Glenmark",     form: "Injection", strength: "100mg/2mL", pack: "Ampoule",       category: "Vitamin",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Vitamin C 500mg",               genericName: "Ascorbic Acid",              brandName: "Limcee",      manufacturer: "Abbott",       form: "Tablet",    strength: "500mg",     pack: "15 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 18 },
  { name: "Zinc 50mg",                     genericName: "Zinc Sulphate",              brandName: "Zincovit",    manufacturer: "Apex",         form: "Tablet",    strength: "50mg",      pack: "15 tabs/strip", category: "Vitamin",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 22 },

  // ── IV Fluids (expanded) ───────────────────────────────────
  { name: "Normal Saline 0.9% 100mL",      genericName: "Sodium Chloride 0.9%",       brandName: "NS",          manufacturer: "Claris",       form: "Injection", strength: "0.9%",      pack: "100mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 100, defaultSalePrice: 28 },
  { name: "Normal Saline 0.9% 1000mL",     genericName: "Sodium Chloride 0.9%",       brandName: "NS",          manufacturer: "Claris",       form: "Injection", strength: "0.9%",      pack: "1000mL bag",    category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 65 },
  { name: "Dextrose 5% 100mL",             genericName: "Dextrose 5%",                brandName: "D5W",         manufacturer: "Claris",       form: "Injection", strength: "5%",        pack: "100mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 28 },
  { name: "Dextrose 25% 25mL Inj",         genericName: "Dextrose 25%",               brandName: "D25",         manufacturer: "Claris",       form: "Injection", strength: "25%",       pack: "Ampoule",       category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 22, isHighAlert: true },
  { name: "Dextrose 50% 25mL Inj",         genericName: "Dextrose 50%",               brandName: "D50",         manufacturer: "Claris",       form: "Injection", strength: "50%",       pack: "Ampoule",       category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 28, isHighAlert: true },
  { name: "DNS 500mL",                     genericName: "Dextrose + Saline",          brandName: "DNS",         manufacturer: "Claris",       form: "Injection", strength: "5%/0.9%",   pack: "500mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 80,  defaultSalePrice: 42 },
  { name: "Isolyte M 500mL",               genericName: "Multiple Electrolyte",       brandName: "Isolyte M",   manufacturer: "Claris",       form: "Injection", strength: "Maintenance",pack:"500mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 95 },
  { name: "Isolyte P 500mL",               genericName: "Multiple Electrolyte",       brandName: "Isolyte P",   manufacturer: "Claris",       form: "Injection", strength: "Paediatric",pack:"500mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Plasmalyte A 500mL",            genericName: "Plasmalyte A",               brandName: "Plasmalyte A",manufacturer: "Baxter",       form: "Injection", strength: "Isotonic",  pack: "500mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 165 },
  { name: "Human Albumin 20% 50mL",        genericName: "Human Serum Albumin",        brandName: "Plasbumin",   manufacturer: "Grifols",      form: "Injection", strength: "20%",       pack: "50mL vial",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 5,  reorderLevel: 15,  defaultSalePrice: 3850, requiresRefrigeration: true },
  { name: "Hetastarch 6% 500mL",           genericName: "Hydroxyethyl Starch",        brandName: "Hesteril",    manufacturer: "Fresenius",    form: "Injection", strength: "6%",        pack: "500mL bag",     category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 485 },
  { name: "Potassium Chloride 15% Inj",    genericName: "KCl",                        brandName: "Potchlor",    manufacturer: "Claris",       form: "Injection", strength: "15%/10mL",  pack: "Ampoule",       category: "IV Fluid",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18, isHighAlert: true },
  { name: "Calcium Gluconate 10% Inj",     genericName: "Calcium Gluconate",          brandName: "Cal Gluconate",manufacturer:"Neon",         form: "Injection", strength: "10%/10mL",  pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 12, isHighAlert: true },
  { name: "Magnesium Sulphate 50% Inj",    genericName: "Magnesium Sulphate",         brandName: "MgSO4",       manufacturer: "Neon",         form: "Injection", strength: "50%/2mL",   pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 9, isHighAlert: true },
  { name: "Sodium Bicarbonate 7.5% Inj",   genericName: "Sodium Bicarbonate",         brandName: "Sodabicarb",  manufacturer: "Claris",       form: "Injection", strength: "7.5%/10mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 15 },

  // ── Emergency Trolley (epinephrine, atropine, naloxone, etc) ──
  { name: "Adrenaline 1mg Inj",            genericName: "Epinephrine",                brandName: "Adrenaline",  manufacturer: "Neon",         form: "Injection", strength: "1mg/1mL",   pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 18, isHighAlert: true },
  { name: "Atropine 0.6mg Inj",            genericName: "Atropine Sulphate",          brandName: "Atropine",    manufacturer: "Neon",         form: "Injection", strength: "0.6mg/1mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 4, isHighAlert: true },
  { name: "Noradrenaline 2mg Inj",         genericName: "Norepinephrine Bitartrate",  brandName: "Noradrenaline",manufacturer:"Samarth",      form: "Injection", strength: "2mg/2mL",   pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 32, isHighAlert: true },
  { name: "Dopamine 200mg Inj",            genericName: "Dopamine HCl",               brandName: "Dopamine",    manufacturer: "Neon",         form: "Injection", strength: "200mg/5mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 32, isHighAlert: true },
  { name: "Dobutamine 250mg Inj",          genericName: "Dobutamine",                 brandName: "Dobutrex",    manufacturer: "Neon",         form: "Injection", strength: "250mg/5mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 95, isHighAlert: true },
  { name: "Vasopressin 20U Inj",           genericName: "Vasopressin",                brandName: "Pitressin",   manufacturer: "Samarth",      form: "Injection", strength: "20IU/1mL",  pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 215, isHighAlert: true },
  { name: "Naloxone 0.4mg Inj",            genericName: "Naloxone HCl",               brandName: "Nalox",       manufacturer: "Samarth",      form: "Injection", strength: "0.4mg/1mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 95 },
  { name: "Flumazenil 0.5mg Inj",          genericName: "Flumazenil",                 brandName: "Lanexat",     manufacturer: "Roche",        form: "Injection", strength: "0.5mg/5mL", pack: "Ampoule",       category: "Emergency",    schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 685 },
  { name: "Lignocaine 2% 30mL Inj",        genericName: "Lidocaine HCl",              brandName: "Xylocaine",   manufacturer: "AstraZeneca",  form: "Injection", strength: "2%",        pack: "30mL vial",     category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Lignocaine + Adrenaline 30mL",  genericName: "Lidocaine/Epinephrine",      brandName: "Xylocaine A", manufacturer: "AstraZeneca",  form: "Injection", strength: "2%+1:200K", pack: "30mL vial",     category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },

  // ── Anesthesia (sedatives, paralytics, induction) ──────────
  { name: "Propofol 200mg Inj",            genericName: "Propofol",                   brandName: "Propofol",    manufacturer: "Claris",       form: "Injection", strength: "200mg/20mL",pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 85, isHighAlert: true },
  { name: "Ketamine 50mg Inj",             genericName: "Ketamine HCl",               brandName: "Ketamine",    manufacturer: "Neon",         form: "Injection", strength: "50mg/10mL", pack: "Vial",          category: "Anesthesia",   schedule: "X",  hsnCode: "30042020", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 115, isHighAlert: true, isNarcotic: true },
  { name: "Thiopentone 500mg Inj",         genericName: "Thiopental Sodium",          brandName: "Thiosol",     manufacturer: "Neon",         form: "Injection", strength: "500mg",     pack: "Vial",          category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 85, isHighAlert: true },
  { name: "Etomidate 20mg Inj",            genericName: "Etomidate",                  brandName: "Hypnomidate", manufacturer: "Janssen",      form: "Injection", strength: "20mg/10mL", pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 15,  defaultSalePrice: 425, isHighAlert: true },
  { name: "Suxamethonium 100mg Inj",       genericName: "Succinylcholine",            brandName: "Scoline",     manufacturer: "Neon",         form: "Injection", strength: "100mg/2mL", pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 32, isHighAlert: true },
  { name: "Atracurium 50mg Inj",           genericName: "Atracurium Besylate",        brandName: "Tracrium",    manufacturer: "GSK",          form: "Injection", strength: "50mg/5mL",  pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145, isHighAlert: true, requiresRefrigeration: true },
  { name: "Vecuronium 4mg Inj",            genericName: "Vecuronium Bromide",         brandName: "Norcuron",    manufacturer: "MSD",          form: "Injection", strength: "4mg",       pack: "Vial",          category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 165, isHighAlert: true },
  { name: "Rocuronium 50mg Inj",           genericName: "Rocuronium Bromide",         brandName: "Esmeron",     manufacturer: "MSD",          form: "Injection", strength: "50mg/5mL",  pack: "Vial",          category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 285, isHighAlert: true, requiresRefrigeration: true },
  { name: "Neostigmine 0.5mg Inj",         genericName: "Neostigmine Methylsulphate", brandName: "Neostigmine", manufacturer: "Neon",         form: "Injection", strength: "0.5mg/1mL", pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 12 },
  { name: "Glycopyrrolate 0.2mg Inj",      genericName: "Glycopyrrolate",             brandName: "Pyrolate",    manufacturer: "Neon",         form: "Injection", strength: "0.2mg/1mL", pack: "Ampoule",       category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 28 },
  { name: "Bupivacaine 0.5% Inj",          genericName: "Bupivacaine HCl",            brandName: "Sensorcaine", manufacturer: "AstraZeneca",  form: "Injection", strength: "0.5%/20mL", pack: "Vial",          category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Bupivacaine Heavy 0.5% Inj",    genericName: "Bupivacaine + Glucose",      brandName: "Sensorcaine Heavy",manufacturer:"AstraZeneca", form: "Injection", strength: "0.5%/4mL", pack: "Ampoule",    category: "Anesthesia",   schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 95 },

  // ── Hormone / Endocrine (Thyroid, Steroidal, Oxytocics) ─────
  { name: "Levothyroxine 50mcg",           genericName: "Levothyroxine Sodium",       brandName: "Eltroxin",    manufacturer: "GSK",          form: "Tablet",    strength: "50mcg",     pack: "100 tabs/bottle",category: "Hormone",     schedule: "H",  hsnCode: "30043910", gstRate: 5,  reorderLevel: 60,  defaultSalePrice: 4 },
  { name: "Levothyroxine 100mcg",          genericName: "Levothyroxine Sodium",       brandName: "Eltroxin",    manufacturer: "GSK",          form: "Tablet",    strength: "100mcg",    pack: "100 tabs/bottle",category: "Hormone",     schedule: "H",  hsnCode: "30043910", gstRate: 5,  reorderLevel: 80,  defaultSalePrice: 6 },
  { name: "Methimazole 5mg",               genericName: "Methimazole",                brandName: "Mercazole",   manufacturer: "Macleods",     form: "Tablet",    strength: "5mg",       pack: "30 tabs/strip", category: "Hormone",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 18 },
  { name: "Oxytocin 5IU Inj",              genericName: "Oxytocin",                   brandName: "Syntocinon",  manufacturer: "Neon",         form: "Injection", strength: "5 IU/1mL",  pack: "Ampoule",       category: "Hormone",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 18, requiresRefrigeration: true },
  { name: "Misoprostol 200mcg",            genericName: "Misoprostol",                brandName: "Cytotec",     manufacturer: "Pfizer",       form: "Tablet",    strength: "200mcg",    pack: "10 tabs/strip", category: "Hormone",      schedule: "H1", hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 22 },
  { name: "Methylergometrine 0.2mg Inj",   genericName: "Methylergometrine Maleate",  brandName: "Methergin",   manufacturer: "Novartis",     form: "Injection", strength: "0.2mg/1mL", pack: "Ampoule",       category: "Hormone",      schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 9, requiresRefrigeration: true },
  { name: "Progesterone 200mg",            genericName: "Micronized Progesterone",    brandName: "Susten",      manufacturer: "Sun Pharma",   form: "Capsule",   strength: "200mg",     pack: "10 caps/strip", category: "Hormone",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 165 },

  // ── Topical / Ophthalmic / ENT ─────────────────────────────
  { name: "Mupirocin 2% Ointment",         genericName: "Mupirocin",                  brandName: "T-Bact",      manufacturer: "GSK",          form: "Ointment",  strength: "2%",        pack: "5g tube",       category: "Topical",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 95 },
  { name: "Fusidic Acid 2% Cream",         genericName: "Fusidic Acid",               brandName: "Fucidin",     manufacturer: "Leo Pharma",   form: "Cream",     strength: "2%",        pack: "15g tube",      category: "Topical",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 145 },
  { name: "Calamine Lotion",               genericName: "Calamine",                   brandName: "Calamine",    manufacturer: "Cipla",        form: "Drops",     strength: "8%",        pack: "100mL bottle",  category: "Topical",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 65 },
  { name: "Permethrin 5% Cream",           genericName: "Permethrin",                 brandName: "Permite",     manufacturer: "Galderma",     form: "Cream",     strength: "5%",        pack: "30g tube",      category: "Topical",      schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Betamethasone 0.1% Cream",      genericName: "Betamethasone Valerate",     brandName: "Betnovate",   manufacturer: "GSK",          form: "Cream",     strength: "0.1%",      pack: "20g tube",      category: "Topical",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 35 },
  { name: "Moxifloxacin Eye Drops",        genericName: "Moxifloxacin",               brandName: "Vigamox",     manufacturer: "Alcon",        form: "Drops",     strength: "0.5%",      pack: "5mL bottle",    category: "Ophthalmic",   schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 115 },
  { name: "Tobramycin + Dexamethasone Eye Drops", genericName: "Tobramycin/Dex",     brandName: "Tobradex",    manufacturer: "Alcon",        form: "Drops",     strength: "0.3%+0.1%", pack: "5mL bottle",    category: "Ophthalmic",   schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 145 },
  { name: "Timolol 0.5% Eye Drops",        genericName: "Timolol Maleate",            brandName: "Timoptic",    manufacturer: "MSD",          form: "Drops",     strength: "0.5%",      pack: "5mL bottle",    category: "Ophthalmic",   schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 25,  defaultSalePrice: 95 },
  { name: "Latanoprost 0.005% Eye Drops",  genericName: "Latanoprost",                brandName: "Xalatan",     manufacturer: "Pfizer",       form: "Drops",     strength: "0.005%",    pack: "2.5mL bottle",  category: "Ophthalmic",   schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 285, requiresRefrigeration: true },
  { name: "Carboxymethylcellulose Eye Drops", genericName: "CMC",                    brandName: "Refresh Tears",manufacturer:"Allergan",      form: "Drops",     strength: "0.5%",      pack: "10mL bottle",   category: "Ophthalmic",   schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 145 },
  { name: "Otrivin Nasal Drops",           genericName: "Xylometazoline",             brandName: "Otrivin",     manufacturer: "Novartis",     form: "Drops",     strength: "0.1%",      pack: "10mL bottle",   category: "ENT",          schedule: "OTC",hsnCode: "30049099", gstRate: 12, reorderLevel: 50,  defaultSalePrice: 95 },
  { name: "Soframycin Skin Cream",         genericName: "Framycetin Sulphate",        brandName: "Soframycin",  manufacturer: "Sanofi",       form: "Cream",     strength: "1%",        pack: "20g tube",      category: "Topical",      schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 40,  defaultSalePrice: 28 },

  // ── Oncology starters (commonly stocked supportive care) ────
  { name: "Filgrastim 300mcg Inj",         genericName: "Filgrastim (G-CSF)",         brandName: "Neukine",     manufacturer: "Intas",        form: "Injection", strength: "300mcg",    pack: "PFS",           category: "Oncology",     schedule: "H",  hsnCode: "30042090", gstRate: 12, reorderLevel: 20,  defaultSalePrice: 485, requiresRefrigeration: true },
  { name: "Methotrexate 7.5mg",            genericName: "Methotrexate",               brandName: "Folitrax",    manufacturer: "Ipca",         form: "Tablet",    strength: "7.5mg",     pack: "10 tabs/strip", category: "Oncology",     schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 30,  defaultSalePrice: 28, isHighAlert: true },
  { name: "Ondansetron 8mg",               genericName: "Ondansetron",                brandName: "Emeset 8",    manufacturer: "Cipla",        form: "Tablet",    strength: "8mg",       pack: "10 tabs/strip", category: "Gastro",       schedule: "H",  hsnCode: "30049099", gstRate: 12, reorderLevel: 60,  defaultSalePrice: 28 },
];

/* ────────────────────────────────────────────────────────────────
   BATCH GENERATION — 1-2 batches per drug, expiry 6m–24m out
──────────────────────────────────────────────────────────────── */
function randInt(lo, hi) { return Math.floor(Math.random() * (hi - lo + 1)) + lo; }
function plusDays(n) { return new Date(Date.now() + n * 86400000); }
function minusDays(n){ return new Date(Date.now() - n * 86400000); }

function generateBatches(drug, supplierIds) {
  const out = [];
  const batchCount = randInt(1, 2);
  for (let i = 0; i < batchCount; i++) {
    const expiryDays = randInt(180, 720);
    const mfgDays    = randInt(30, 270);
    const qty        = randInt(Math.max(20, Math.round(drug.reorderLevel * 0.6)),
                               Math.max(50, Math.round(drug.reorderLevel * 2.2)));
    const purchase   = Math.max(0.5, drug.defaultSalePrice * 0.62);
    const mrp        = Math.round(drug.defaultSalePrice * 1.18 * 100) / 100;
    const supplier   = supplierIds[randInt(0, supplierIds.length - 1)];
    const ymd        = new Date().toISOString().slice(0,10).replace(/-/g, "");
    const batchNo    = `${drug.name.split(" ")[0].substring(0, 3).toUpperCase()}-${ymd}-R${String(i + 1).padStart(2, "0")}${String(randInt(1, 99)).padStart(2, "0")}`;
    out.push({
      drugId: drug._id, drugName: drug.name,
      batchNo,
      expiryDate: plusDays(expiryDays),
      mfgDate:    minusDays(mfgDays),
      quantityIn: qty, remaining: qty,
      purchaseRate: Math.round(purchase * 100) / 100,
      mrp,
      salePrice: drug.defaultSalePrice,
      supplierId: supplier.id, supplierName: supplier.name,
      grnNumber: `GRN-R-${ymd}-${randInt(1000, 9999)}`,
      invoiceNo: `INV/R/${randInt(2025, 2026)}/${randInt(1000, 9999)}`,
      invoiceDate: minusDays(mfgDays - randInt(0, 7)),
      location: "Main Pharmacy",
      createdBy: "Restock script",
    });
  }
  return out;
}

/* ────────────────────────────────────────────────────────────────
   MAIN
──────────────────────────────────────────────────────────────── */
(async () => {
  await connectDB();
  console.log("\n┌──────────────────────────────────────────────────");
  console.log("│  Pharmacy RESTOCK — ", RESTOCK.length, "candidate drugs");
  console.log("└──────────────────────────────────────────────────\n");

  // 0. Optional cleanup of pre-existing test rows
  if (CLEAN_TEST) {
    const before = await Drug.countDocuments({ name: { $in: TEST_NAMES } });
    if (before) {
      const drugs = await Drug.find({ name: { $in: TEST_NAMES } }, "_id").lean();
      const ids = drugs.map(d => d._id);
      await DrugBatch.deleteMany({ drugId: { $in: ids } });
      await Drug.deleteMany({ _id: { $in: ids } });
      console.log(`  ✓ Cleaned ${before} test rows (probe/test/audit entries)\n`);
    }
  }

  // 1. Get suppliers (reuse from base seed)
  const existing = await Supplier.find({ isActive: true }).lean();
  const supplierIds = existing.map(s => ({ id: s._id, name: s.name }));
  if (!supplierIds.length) {
    console.error("  ✗ No suppliers found. Run seedPharmacy.js first.");
    process.exit(1);
  }
  console.log(`  • Using ${supplierIds.length} existing suppliers\n`);

  // 2. Drugs — upsert new, skip existing
  let drugCreated = 0, drugSkipped = 0;
  const newDrugs = [];
  for (const d of RESTOCK) {
    if (BATCHES_ONLY) {
      const e = await Drug.findOne({ name: d.name });
      if (e) newDrugs.push(e);
      continue;
    }
    const e = await Drug.findOne({ name: d.name });
    if (e) { drugSkipped++; continue; }
    const created = await Drug.create({ ...d, createdBy: "Restock script (R7gz)" });
    drugCreated++;
    newDrugs.push(created);
  }
  console.log(`  ✓ Drugs: ${drugCreated} created, ${drugSkipped} already present\n`);

  // 3. Batches
  let batchCreated = 0;
  for (const drug of newDrugs) {
    const has = await DrugBatch.countDocuments({ drugId: drug._id });
    if (has > 0) continue;
    const batches = generateBatches(drug, supplierIds);
    if (batches.length) {
      await DrugBatch.insertMany(batches);
      batchCreated += batches.length;
    }
  }
  console.log(`  ✓ Batches: ${batchCreated} created\n`);

  // 4. Final summary
  const total = await Drug.countDocuments({ isActive: true });
  const byCategory = await Drug.aggregate([
    { $match: { isActive: true } },
    { $group: { _id: "$category", count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);
  console.log(`\n  ★ Active drug count: ${total}`);
  console.log("    By category:");
  byCategory.forEach(c => console.log(`      ${String(c._id || "Other").padEnd(18)} ${c.count}`));

  console.log("\n  Done.\n");
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
