// seeders/serviceMasterSeeder.js
// ═══════════════════════════════════════════════════════════════
// SERVICE MASTER SEED DATA
// IPD, OPD, Emergency, Daycare — sab services
// Run once after deployment: POST /api/services/seed
// ═══════════════════════════════════════════════════════════════

const ServiceMaster = require(".././models/ServiceMaster/serviceMasterModel");
const ServicePricing = require("../../Backend/models/ServicePricing/ServicePricingModel");

const SERVICES = [
  // ────────────────────────────────────────────────────────────
  // 1. IPD — ADMISSION REGISTRATION
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-ADM-001",
    serviceName: "Admission Processing Fee",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 101,
  },
  {
    serviceCode: "IPD-ADM-002",
    serviceName: "Bed Allocation Charge",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 102,
  },
  {
    serviceCode: "IPD-ADM-003",
    serviceName: "Admission Kit Charge",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 103,
  },
  {
    serviceCode: "IPD-ADM-004",
    serviceName: "Patient ID Band Charge",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 50,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 104,
  },
  {
    serviceCode: "IPD-ADM-005",
    serviceName: "File Opening Charge (IPD)",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 105,
  },
  {
    serviceCode: "IPD-ADM-006",
    serviceName: "Initial Assessment Fee",
    domain: "IPD",
    category: "REGISTRATION",
    subCategory: "Admission",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 106,
  },

  // ────────────────────────────────────────────────────────────
  // 2. IPD — ROOM & ACCOMMODATION  (isAutoCharged: true)
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-RM-001",
    serviceName: "General Ward Bed",
    domain: "IPD",
    category: "ROOM",
    subCategory: "General Rooms",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 600,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 201,
  },
  {
    serviceCode: "IPD-RM-002",
    serviceName: "Semi-Private Room",
    domain: "IPD",
    category: "ROOM",
    subCategory: "General Rooms",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1200,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 202,
  },
  {
    serviceCode: "IPD-RM-003",
    serviceName: "Private Room",
    domain: "IPD",
    category: "ROOM",
    subCategory: "General Rooms",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 2000,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 203,
  },
  {
    serviceCode: "IPD-RM-004",
    serviceName: "Deluxe Room",
    domain: "IPD",
    category: "ROOM",
    subCategory: "General Rooms",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 3500,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 204,
  },
  {
    serviceCode: "IPD-RM-005",
    serviceName: "Suite Room",
    domain: "IPD",
    category: "ROOM",
    subCategory: "General Rooms",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 5000,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 205,
  },
  {
    serviceCode: "IPD-RM-006",
    serviceName: "Extra Bed",
    domain: "IPD",
    category: "ROOM",
    subCategory: "Add-On Beds",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 400,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 206,
  },
  {
    serviceCode: "IPD-RM-007",
    serviceName: "Attendant Bed",
    domain: "IPD",
    category: "ROOM",
    subCategory: "Add-On Beds",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 207,
  },
  {
    serviceCode: "IPD-RM-008",
    serviceName: "Day Care Bed",
    domain: "IPD",
    category: "ROOM",
    subCategory: "Add-On Beds",
    applicableTo: ["DAYCARE"],
    billingType: "PER_DAY",
    defaultPrice: 800,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 208,
  },
  {
    serviceCode: "IPD-RM-009",
    serviceName: "Hourly Bed Charge",
    domain: "IPD",
    category: "ROOM",
    subCategory: "Add-On Beds",
    applicableTo: ["IPD", "DAYCARE"],
    billingType: "PER_HOUR",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 209,
  },
  {
    serviceCode: "IPD-RM-010",
    serviceName: "Late Discharge Charge",
    domain: "IPD",
    category: "ROOM",
    subCategory: "Add-On Beds",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 210,
  },

  // ────────────────────────────────────────────────────────────
  // 3. IPD — DOCTOR SERVICES
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-DOC-001",
    serviceName: "Initial Consultant Visit",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Admission Consultation",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 301,
  },
  {
    serviceCode: "IPD-DOC-002",
    serviceName: "General Physician Ward Visit",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 400,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 302,
  },
  {
    serviceCode: "IPD-DOC-003",
    serviceName: "Specialist Ward Visit",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 700,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 303,
  },
  {
    serviceCode: "IPD-DOC-004",
    serviceName: "Super Specialist Ward Visit",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 1200,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 304,
  },
  {
    serviceCode: "IPD-DOC-005",
    serviceName: "Night Visit Surcharge",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 600,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 305,
  },
  {
    serviceCode: "IPD-DOC-006",
    serviceName: "Holiday Visit Surcharge",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 600,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 306,
  },
  {
    serviceCode: "IPD-DOC-007",
    serviceName: "Emergency Doctor Visit",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "PER_VISIT",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 307,
  },
  {
    serviceCode: "IPD-DOC-008",
    serviceName: "Multidisciplinary Review",
    domain: "IPD",
    category: "DOCTOR",
    subCategory: "Daily Ward Visits",
    applicableTo: ["IPD"],
    billingType: "PER_SESSION",
    defaultPrice: 1500,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 308,
  },

  // ────────────────────────────────────────────────────────────
  // 4. IPD — NURSING & CARE
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-NUR-001",
    serviceName: "General Ward Nursing Charge",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Nursing",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 400,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 401,
  },
  {
    serviceCode: "IPD-NUR-002",
    serviceName: "High Dependency Nursing",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Nursing",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 800,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 402,
  },
  {
    serviceCode: "IPD-NUR-003",
    serviceName: "Private Duty Nurse",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Nursing",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1200,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 403,
  },
  {
    serviceCode: "IPD-NUR-004",
    serviceName: "1:1 Special Nursing",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Nursing",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1500,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 404,
  },
  {
    serviceCode: "IPD-NUR-005",
    serviceName: "Vital Signs Monitoring",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Monitoring",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 405,
  },
  {
    serviceCode: "IPD-NUR-006",
    serviceName: "Fluid Balance Monitoring",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Monitoring",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 406,
  },
  {
    serviceCode: "IPD-NUR-007",
    serviceName: "Post-Operative Monitoring",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Monitoring",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 407,
  },
  {
    serviceCode: "IPD-NUR-008",
    serviceName: "Fall Risk Monitoring",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Monitoring",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 408,
  },
  {
    serviceCode: "IPD-NUR-009",
    serviceName: "Wound Dressing",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Bedside Care",
    applicableTo: ["IPD", "OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 409,
    doctorOrderCategory: "Nursing",
  },
  {
    serviceCode: "IPD-NUR-010",
    serviceName: "Urinary Catheter Care",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Bedside Care",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 410,
    doctorOrderCategory: "Nursing",
  },
  {
    serviceCode: "IPD-NUR-011",
    serviceName: "Pressure Sore Management",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Bedside Care",
    applicableTo: ["IPD"],
    billingType: "PER_SESSION",
    defaultPrice: 400,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 411,
  },
  {
    serviceCode: "IPD-NUR-012",
    serviceName: "Feeding Assistance",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Bedside Care",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 412,
  },
  {
    serviceCode: "IPD-NUR-013",
    serviceName: "Bed Bath Assistance",
    domain: "IPD",
    category: "NURSING",
    subCategory: "Bedside Care",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 413,
  },

  // ────────────────────────────────────────────────────────────
  // 5. IPD — PROCEDURES
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-PRC-001",
    serviceName: "Suturing",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 501,
  },
  {
    serviceCode: "IPD-PRC-002",
    serviceName: "IV Line Insertion",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 502,
  },
  {
    serviceCode: "IPD-PRC-003",
    serviceName: "Urinary Catheter Insertion",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 400,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 503,
  },
  {
    serviceCode: "IPD-PRC-004",
    serviceName: "Wound Debridement",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 504,
  },
  {
    serviceCode: "IPD-PRC-005",
    serviceName: "Central Line Insertion",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Major Bedside Procedures",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 3000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 505,
  },
  {
    serviceCode: "IPD-PRC-006",
    serviceName: "Endotracheal Intubation",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Major Bedside Procedures",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 2000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 506,
  },
  {
    serviceCode: "IPD-PRC-007",
    serviceName: "Chest Tube Insertion",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Major Bedside Procedures",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 4000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 507,
  },
  {
    serviceCode: "IPD-PRC-008",
    serviceName: "Tracheostomy",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Major Bedside Procedures",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 5000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 508,
  },

  // ────────────────────────────────────────────────────────────
  // 6. IPD — OPERATION THEATRE
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-OT-001",
    serviceName: "Major OT Usage",
    domain: "IPD",
    category: "OT",
    subCategory: "OT Usage",
    applicableTo: ["IPD"],
    billingType: "PER_HOUR",
    defaultPrice: 3000,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 601,
  },
  {
    serviceCode: "IPD-OT-002",
    serviceName: "Minor OT Usage",
    domain: "IPD",
    category: "OT",
    subCategory: "OT Usage",
    applicableTo: ["IPD"],
    billingType: "PER_HOUR",
    defaultPrice: 1500,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 602,
  },
  {
    serviceCode: "IPD-OT-003",
    serviceName: "Emergency OT Usage",
    domain: "IPD",
    category: "OT",
    subCategory: "OT Usage",
    applicableTo: ["IPD", "EMERGENCY"],
    billingType: "PER_HOUR",
    defaultPrice: 4000,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 603,
  },
  {
    serviceCode: "IPD-OT-004",
    serviceName: "OT Setup Charges",
    domain: "IPD",
    category: "OT",
    subCategory: "OT Usage",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 1000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 604,
  },
  {
    serviceCode: "IPD-OT-005",
    serviceName: "OT Sterilization Charges",
    domain: "IPD",
    category: "OT",
    subCategory: "OT Usage",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 605,
  },
  {
    serviceCode: "IPD-OT-006",
    serviceName: "General Anaesthesia",
    domain: "IPD",
    category: "OT",
    subCategory: "Anaesthesia",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 3000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 606,
  },
  {
    serviceCode: "IPD-OT-007",
    serviceName: "Spinal Anaesthesia",
    domain: "IPD",
    category: "OT",
    subCategory: "Anaesthesia",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 2000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 607,
  },
  {
    serviceCode: "IPD-OT-008",
    serviceName: "Local Anaesthesia",
    domain: "IPD",
    category: "OT",
    subCategory: "Anaesthesia",
    applicableTo: ["IPD", "OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 608,
  },
  {
    serviceCode: "IPD-OT-009",
    serviceName: "Epidural Anaesthesia",
    domain: "IPD",
    category: "OT",
    subCategory: "Anaesthesia",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 2500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 609,
  },
  {
    serviceCode: "IPD-OT-010",
    serviceName: "Recovery Room (PACU) Charges",
    domain: "IPD",
    category: "OT",
    subCategory: "Recovery",
    applicableTo: ["IPD"],
    billingType: "PER_HOUR",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 610,
  },

  // ────────────────────────────────────────────────────────────
  // 7. IPD — ICU SERVICES
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-ICU-001",
    serviceName: "ICU Bed Charge",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 4000,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 701,
  },
  {
    serviceCode: "IPD-ICU-002",
    serviceName: "ICU Cardiac Monitoring",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1000,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 702,
  },
  {
    serviceCode: "IPD-ICU-003",
    serviceName: "Ventilator Usage",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_HOUR",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 703,
  },
  {
    serviceCode: "IPD-ICU-004",
    serviceName: "BiPAP / CPAP Usage",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1200,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 704,
  },
  {
    serviceCode: "IPD-ICU-005",
    serviceName: "ICU Nursing Charge",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 1500,
    isAutoCharged: true,
    unitLabel: "per day",
    displayOrder: 705,
  },
  {
    serviceCode: "IPD-ICU-006",
    serviceName: "Intensivist Visit",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_VISIT",
    defaultPrice: 1000,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 706,
  },
  {
    serviceCode: "IPD-ICU-007",
    serviceName: "Isolation Surcharge",
    domain: "IPD",
    category: "ICU",
    subCategory: "ICU",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 707,
  },

  // ────────────────────────────────────────────────────────────
  // 8. IPD — SUPPORT SERVICES
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-SUP-001",
    serviceName: "Patient Transport (Internal)",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_SESSION",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 801,
  },
  {
    serviceCode: "IPD-SUP-002",
    serviceName: "Dietician Consultation",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_SESSION",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 802,
    // R7bm-F10 / R7bl seed-tax: HSN 999316 (Human health services n.e.c.),
    // 18% GST on diet/consultation services per CBIC notification 11/2017-CT.
    isTaxable: true,
    taxPercentage: 18,
    hsnSacCode: "999316",
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "IPD-SUP-003",
    serviceName: "Special Diet Charges",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 803,
    // R7bm-F10 / R7bl seed-tax: HSN 999316 (Human health services n.e.c.),
    // 18% GST on diet/consultation services per CBIC notification 11/2017-CT.
    isTaxable: true,
    taxPercentage: 18,
    hsnSacCode: "999316",
    doctorOrderCategory: "Diet",
  },
  // R7bm-F10 / R7bl seed-add: IPD physiotherapy session — referenced by
  // services/Clinical/physioService.js, models/Clinical/PhysioSessionModel.js,
  // and the kitchenIndentService.js but had no ServiceMaster row, breaking
  // bill-line creation for ward physio sessions.
  // Rate (₹500/session) and HSN (999316 — same human-health-services SAC
  // as other in-hospital therapy services) are reasonable defaults — verify
  // against the hospital's tariff card before go-live.
  {
    serviceCode: "IPD-PHY-001",
    serviceName: "IPD Physiotherapy Session",
    domain: "IPD",
    category: "PROCEDURE",
    subCategory: "Physiotherapy",
    applicableTo: ["IPD"],
    billingType: "PER_SESSION",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 850,
    isTaxable: true,
    taxPercentage: 18,
    hsnSacCode: "999316",
    serviceType: "procedure",
    chargeableBy: ["Doctor", "Nurse"],
    doctorOrderCategory: "Physiotherapy",
  },
  {
    serviceCode: "IPD-SUP-004",
    serviceName: "Biomedical Waste Handling",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 804,
  },
  {
    serviceCode: "IPD-SUP-005",
    serviceName: "Linen Charges",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 805,
  },
  {
    serviceCode: "IPD-SUP-006",
    serviceName: "Laundry Charges",
    domain: "IPD",
    category: "SUPPORT",
    subCategory: "Support",
    applicableTo: ["IPD"],
    billingType: "PER_DAY",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "per day",
    displayOrder: 806,
  },

  // ────────────────────────────────────────────────────────────
  // 9. IPD — DISCHARGE & ADMIN
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-DIS-001",
    serviceName: "Discharge Summary Preparation",
    domain: "IPD",
    category: "DISCHARGE",
    subCategory: "Discharge",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 901,
  },
  {
    serviceCode: "IPD-DIS-002",
    serviceName: "Final Bill Processing",
    domain: "IPD",
    category: "DISCHARGE",
    subCategory: "Discharge",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 902,
  },
  {
    serviceCode: "IPD-DIS-003",
    serviceName: "Insurance / TPA Processing Fee",
    domain: "IPD",
    category: "DISCHARGE",
    subCategory: "Discharge",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 903,
  },
  {
    serviceCode: "IPD-DIS-004",
    serviceName: "Medical Record Compilation",
    domain: "IPD",
    category: "DISCHARGE",
    subCategory: "Discharge",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 904,
  },

  // ────────────────────────────────────────────────────────────
  // 10. IPD — PACKAGES
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "IPD-PKG-001",
    serviceName: "Surgery Package",
    domain: "IPD",
    category: "PACKAGE",
    subCategory: "Packages",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 25000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1001,
  },
  {
    serviceCode: "IPD-PKG-002",
    serviceName: "ICU Package",
    domain: "IPD",
    category: "PACKAGE",
    subCategory: "Packages",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 15000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1002,
  },
  {
    serviceCode: "IPD-PKG-003",
    serviceName: "Maternity Package",
    domain: "IPD",
    category: "PACKAGE",
    subCategory: "Packages",
    applicableTo: ["IPD"],
    billingType: "ONE_TIME",
    defaultPrice: 20000,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1003,
  },

  // ────────────────────────────────────────────────────────────
  // 11. OPD — REGISTRATION & CONSULTATION
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "OPD-REG-001",
    serviceName: "New OPD Registration",
    domain: "OPD",
    category: "REGISTRATION",
    subCategory: "Registration",
    applicableTo: ["OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1101,
  },
  {
    serviceCode: "OPD-REG-002",
    serviceName: "Follow-up Registration",
    domain: "OPD",
    category: "REGISTRATION",
    subCategory: "Registration",
    applicableTo: ["OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 50,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1102,
  },
  {
    serviceCode: "OPD-REG-003",
    serviceName: "Revisit (Within Validity)",
    domain: "OPD",
    category: "REGISTRATION",
    subCategory: "Registration",
    applicableTo: ["OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 30,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1103,
  },
  {
    serviceCode: "OPD-REG-004",
    serviceName: "File Opening Charge (OPD)",
    domain: "OPD",
    category: "REGISTRATION",
    subCategory: "Registration",
    applicableTo: ["OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 50,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1104,
  },
  {
    serviceCode: "OPD-CON-001",
    serviceName: "General Physician Consultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_VISIT",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1201,
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "OPD-CON-002",
    serviceName: "Specialist Consultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_VISIT",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1202,
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "OPD-CON-003",
    serviceName: "Super Specialist Consultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_VISIT",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1203,
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "OPD-CON-004",
    serviceName: "Senior Consultant Consultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_VISIT",
    defaultPrice: 700,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1204,
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "OPD-CON-005",
    serviceName: "Follow-up Consultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_VISIT",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1205,
    doctorOrderCategory: "Consultation",
  },
  {
    serviceCode: "OPD-CON-006",
    serviceName: "Teleconsultation",
    domain: "OPD",
    category: "CONSULTATION",
    subCategory: "Consultation",
    applicableTo: ["OPD"],
    billingType: "PER_SESSION",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1206,
    doctorOrderCategory: "Consultation",
  },

  // ────────────────────────────────────────────────────────────
  // 12. OPD — PROCEDURES & NURSING
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "OPD-PRC-001",
    serviceName: "Suturing (OPD)",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["OPD"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1301,
  },
  {
    serviceCode: "OPD-PRC-002",
    serviceName: "Wound Dressing (OPD)",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["OPD"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1302,
  },
  {
    serviceCode: "OPD-PRC-003",
    serviceName: "Nebulization",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["OPD"],
    billingType: "PER_SESSION",
    defaultPrice: 150,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1303,
  },
  {
    serviceCode: "OPD-PRC-004",
    serviceName: "IV Cannula Insertion (OPD)",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["OPD"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1304,
  },
  {
    serviceCode: "OPD-PRC-005",
    serviceName: "Injection Administration",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Minor Procedures",
    applicableTo: ["OPD"],
    billingType: "PER_SESSION",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1305,
  },
  {
    serviceCode: "OPD-PRC-006",
    serviceName: "Minor OT Procedure (OPD)",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Specialised OPD",
    applicableTo: ["OPD"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 1000,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1306,
  },
  {
    serviceCode: "OPD-PRC-007",
    serviceName: "Cast / Splint Application",
    domain: "OPD",
    category: "PROCEDURE",
    subCategory: "Specialised OPD",
    applicableTo: ["OPD"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1307,
  },
  {
    serviceCode: "OPD-NUR-001",
    serviceName: "OPD Vital Monitoring",
    domain: "OPD",
    category: "NURSING",
    subCategory: "OPD Nursing",
    applicableTo: ["OPD"],
    billingType: "PER_SESSION",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1401,
  },
  {
    serviceCode: "OPD-NUR-002",
    serviceName: "Injection Room Usage",
    domain: "OPD",
    category: "NURSING",
    subCategory: "OPD Nursing",
    applicableTo: ["OPD"],
    billingType: "PER_SESSION",
    defaultPrice: 50,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1402,
  },

  // ────────────────────────────────────────────────────────────
  // 13. DAYCARE
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "OPD-DAY-001",
    serviceName: "Daycare Bed (Up to 6 Hours)",
    domain: "DAYCARE",
    category: "DAYCARE",
    subCategory: "Daycare",
    applicableTo: ["DAYCARE"],
    billingType: "PER_SESSION",
    defaultPrice: 1000,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1501,
  },
  {
    serviceCode: "OPD-DAY-002",
    serviceName: "Hourly Observation Bed",
    domain: "DAYCARE",
    category: "DAYCARE",
    subCategory: "Daycare",
    applicableTo: ["DAYCARE"],
    billingType: "PER_HOUR",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 1502,
  },
  {
    serviceCode: "OPD-DAY-003",
    serviceName: "Recovery Room Usage (Daycare)",
    domain: "DAYCARE",
    category: "DAYCARE",
    subCategory: "Daycare",
    applicableTo: ["DAYCARE"],
    billingType: "PER_HOUR",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 1503,
  },

  // ────────────────────────────────────────────────────────────
  // 14. EMERGENCY
  // ────────────────────────────────────────────────────────────
  {
    serviceCode: "ER-REG-001",
    serviceName: "Emergency Registration",
    domain: "EMERGENCY",
    category: "REGISTRATION",
    subCategory: "ER Registration",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1601,
  },
  {
    serviceCode: "ER-REG-002",
    serviceName: "Casualty File Opening",
    domain: "EMERGENCY",
    category: "REGISTRATION",
    subCategory: "ER Registration",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 100,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1602,
  },
  {
    serviceCode: "ER-REG-003",
    serviceName: "Medico-Legal Case Registration",
    domain: "EMERGENCY",
    category: "REGISTRATION",
    subCategory: "ER Registration",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1603,
  },
  {
    serviceCode: "ER-TRI-001",
    serviceName: "Triage Assessment",
    domain: "EMERGENCY",
    category: "CONSULTATION",
    subCategory: "Triage",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1701,
  },
  {
    serviceCode: "ER-TRI-002",
    serviceName: "Emergency Physician Initial Assessment",
    domain: "EMERGENCY",
    category: "CONSULTATION",
    subCategory: "Triage",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 1702,
  },
  {
    serviceCode: "ER-CON-001",
    serviceName: "Emergency Physician Consultation",
    domain: "EMERGENCY",
    category: "CONSULTATION",
    subCategory: "ER Consultation",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_VISIT",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1801,
  },
  {
    serviceCode: "ER-CON-002",
    serviceName: "Specialist On-Call Visit",
    domain: "EMERGENCY",
    category: "CONSULTATION",
    subCategory: "ER Consultation",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_VISIT",
    defaultPrice: 800,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1802,
  },
  {
    serviceCode: "ER-CON-003",
    serviceName: "Night Emergency Doctor Visit",
    domain: "EMERGENCY",
    category: "CONSULTATION",
    subCategory: "ER Consultation",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_VISIT",
    defaultPrice: 700,
    isAutoCharged: false,
    unitLabel: "per visit",
    displayOrder: 1803,
  },
  {
    serviceCode: "ER-PRC-001",
    serviceName: "Suturing (Emergency)",
    domain: "EMERGENCY",
    category: "PROCEDURE",
    subCategory: "ER Procedures",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 600,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1901,
  },
  {
    serviceCode: "ER-PRC-002",
    serviceName: "Wound Dressing (Emergency)",
    domain: "EMERGENCY",
    category: "PROCEDURE",
    subCategory: "ER Procedures",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 250,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1902,
  },
  {
    serviceCode: "ER-PRC-003",
    serviceName: "IV Cannulation (Emergency)",
    domain: "EMERGENCY",
    category: "PROCEDURE",
    subCategory: "ER Procedures",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1903,
  },
  {
    serviceCode: "ER-PRC-004",
    serviceName: "Intubation (Emergency)",
    domain: "EMERGENCY",
    category: "PROCEDURE",
    subCategory: "ER Procedures",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_PROCEDURE",
    defaultPrice: 2500,
    isAutoCharged: false,
    unitLabel: "per procedure",
    displayOrder: 1904,
  },
  {
    serviceCode: "ER-PRC-005",
    serviceName: "CPR / Resuscitation",
    domain: "EMERGENCY",
    category: "PROCEDURE",
    subCategory: "ER Procedures",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_SESSION",
    defaultPrice: 3000,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 1905,
  },
  {
    serviceCode: "ER-OBS-001",
    serviceName: "Emergency Bed (Up to 6 Hours)",
    domain: "EMERGENCY",
    category: "ROOM",
    subCategory: "ER Observation",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_SESSION",
    defaultPrice: 800,
    isAutoCharged: true,
    unitLabel: "per session",
    displayOrder: 2001,
  },
  {
    serviceCode: "ER-OBS-002",
    serviceName: "Emergency Hourly Bed Charge",
    domain: "EMERGENCY",
    category: "ROOM",
    subCategory: "ER Observation",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_HOUR",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 2002,
  },
  {
    serviceCode: "ER-OBS-003",
    serviceName: "Cardiac Monitor Charge",
    domain: "EMERGENCY",
    category: "NURSING",
    subCategory: "ER Monitoring",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_HOUR",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 2003,
  },
  {
    serviceCode: "ER-OBS-004",
    serviceName: "Oxygen Therapy",
    domain: "EMERGENCY",
    category: "NURSING",
    subCategory: "ER Monitoring",
    applicableTo: ["EMERGENCY", "IPD"],
    billingType: "PER_HOUR",
    defaultPrice: 200,
    isAutoCharged: false,
    unitLabel: "per hour",
    displayOrder: 2004,
    doctorOrderCategory: "Oxygen",
  },
  {
    serviceCode: "ER-NUR-001",
    serviceName: "Emergency Nursing Charge",
    domain: "EMERGENCY",
    category: "NURSING",
    subCategory: "ER Nursing",
    applicableTo: ["EMERGENCY"],
    billingType: "PER_SESSION",
    defaultPrice: 400,
    isAutoCharged: false,
    unitLabel: "per session",
    displayOrder: 2101,
  },
  {
    serviceCode: "ER-SUP-001",
    serviceName: "Emergency Ambulance (Internal)",
    domain: "EMERGENCY",
    category: "SUPPORT",
    subCategory: "ER Support",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 500,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 2201,
  },
  {
    serviceCode: "ER-SUP-002",
    serviceName: "ER Consumables Kit",
    domain: "EMERGENCY",
    category: "SUPPORT",
    subCategory: "ER Support",
    applicableTo: ["EMERGENCY"],
    billingType: "ONE_TIME",
    defaultPrice: 300,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 2202,
  },
  {
    serviceCode: "ER-SUP-003",
    serviceName: "Plaster of Paris (POP) Set",
    domain: "EMERGENCY",
    category: "SUPPORT",
    subCategory: "ER Support",
    applicableTo: ["EMERGENCY", "OPD"],
    billingType: "ONE_TIME",
    defaultPrice: 600,
    isAutoCharged: false,
    unitLabel: "one time",
    displayOrder: 2203,
  },

  // ════════════════════════════════════════════════════════════════
  // ENGINE-LEVEL CODES — codes that autoBillingService.js posts when
  // it fires onOPDRegistered / onAdmissionCreated / onEmergencyVisit /
  // onDoctorNoteSaved / onNurseNoteSaved. Without these rows in
  // ServiceMaster the engine still works (via unitPriceOverride
  // fallback) but ServicePricing tariff overrides (CASH/TPA/CORPORATE)
  // never apply — so this seed is what unlocks proper rate-card
  // overrides for the auto-billed line items.
  // ════════════════════════════════════════════════════════════════

  // ── Registration fees (one-time, per visit-type) ─────────────────
  { serviceCode: "REG-OPD",       serviceName: "OPD Registration Fee",       domain: "OPD",       category: "REGISTRATION", applicableTo: ["OPD"],       billingType: "ONE_TIME", defaultPrice: 100, isAutoCharged: true, unitLabel: "one time", displayOrder: 9001 },
  { serviceCode: "REG-IPD",       serviceName: "IPD Registration Fee",       domain: "IPD",       category: "REGISTRATION", applicableTo: ["IPD"],       billingType: "ONE_TIME", defaultPrice: 200, isAutoCharged: true, unitLabel: "one time", displayOrder: 9002 },
  { serviceCode: "REG-DAYCARE",   serviceName: "Day Care Registration Fee",  domain: "DAYCARE",   category: "REGISTRATION", applicableTo: ["DAYCARE"],   billingType: "ONE_TIME", defaultPrice: 150, isAutoCharged: true, unitLabel: "one time", displayOrder: 9003 },
  { serviceCode: "REG-EMERGENCY", serviceName: "Emergency Registration Fee", domain: "EMERGENCY", category: "REGISTRATION", applicableTo: ["EMERGENCY"], billingType: "ONE_TIME", defaultPrice: 300, isAutoCharged: true, unitLabel: "one time", displayOrder: 9004 },
  { serviceCode: "REG-SERVICES",  serviceName: "Services Registration Fee",  domain: "COMMON",    category: "REGISTRATION", applicableTo: ["ALL"],       billingType: "ONE_TIME", defaultPrice: 50,  isAutoCharged: true, unitLabel: "one time", displayOrder: 9005 },

  // ── Admission processing (one-time, per admission-type) ──────────
  { serviceCode: "ADM-OPD",       serviceName: "OPD Admission Processing",       domain: "OPD",       category: "REGISTRATION", applicableTo: ["OPD"],       billingType: "ONE_TIME", defaultPrice: 0,   isAutoCharged: true, unitLabel: "one time", displayOrder: 9011 },
  { serviceCode: "ADM-IPD",       serviceName: "IPD Admission Processing",       domain: "IPD",       category: "REGISTRATION", applicableTo: ["IPD"],       billingType: "ONE_TIME", defaultPrice: 500, isAutoCharged: true, unitLabel: "one time", displayOrder: 9012 },
  { serviceCode: "ADM-DAYCARE",   serviceName: "Day Care Admission Processing",  domain: "DAYCARE",   category: "REGISTRATION", applicableTo: ["DAYCARE"],   billingType: "ONE_TIME", defaultPrice: 300, isAutoCharged: true, unitLabel: "one time", displayOrder: 9013 },
  { serviceCode: "ADM-EMERGENCY", serviceName: "Emergency Admission Processing", domain: "EMERGENCY", category: "REGISTRATION", applicableTo: ["EMERGENCY"], billingType: "ONE_TIME", defaultPrice: 400, isAutoCharged: true, unitLabel: "one time", displayOrder: 9014 },

  // ── Bed/Room charges (per day, by room category) ─────────────────
  // The engine resolves these via the admission's room → roomCategory
  // → defaultPricing.perBedDailyRate. ServiceMaster row exists purely
  // to anchor the line item; the actual rate comes from RoomCategory.
  { serviceCode: "BED",                 serviceName: "Bed Charge (Daily)",                domain: "IPD", category: "ROOM", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 1500, isAutoCharged: true, unitLabel: "per day", displayOrder: 9020 },
  { serviceCode: "BED-GENERAL",         serviceName: "Bed — General Ward (Daily)",        domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 1000, isAutoCharged: true, unitLabel: "per day", displayOrder: 9021 },
  { serviceCode: "BED-SEMI_PRIVATE",    serviceName: "Bed — Semi-Private (Daily)",        domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 1800, isAutoCharged: true, unitLabel: "per day", displayOrder: 9022 },
  { serviceCode: "BED-PRIVATE",         serviceName: "Bed — Private Room (Daily)",        domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 3000, isAutoCharged: true, unitLabel: "per day", displayOrder: 9023 },
  { serviceCode: "BED-DELUXE",          serviceName: "Bed — Deluxe Suite (Daily)",        domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 5000, isAutoCharged: true, unitLabel: "per day", displayOrder: 9024 },
  { serviceCode: "BED-ICU",             serviceName: "Bed — ICU (Daily)",                 domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 6000, isAutoCharged: true, unitLabel: "per day", displayOrder: 9025 },
  { serviceCode: "BED-NICU",            serviceName: "Bed — NICU (Daily)",                domain: "IPD", category: "ROOM", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 7000, isAutoCharged: true, unitLabel: "per day", displayOrder: 9026 },
  { serviceCode: "BED-DAYCARE",         serviceName: "Bed — Day Care (Daily)",            domain: "DAYCARE", category: "ROOM", applicableTo: ["DAYCARE"], billingType: "PER_DAY", defaultPrice: 800, isAutoCharged: true, unitLabel: "per day", displayOrder: 9027 },

  // ── Nursing charges (per day, by room category) ──────────────────
  { serviceCode: "NURSING",             serviceName: "Nursing Charge (Daily)",            domain: "IPD", category: "NURSING", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 300, isAutoCharged: true, unitLabel: "per day", displayOrder: 9030 },
  { serviceCode: "NURSING-GENERAL",     serviceName: "Nursing — General Ward (Daily)",    domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 200, isAutoCharged: true, unitLabel: "per day", displayOrder: 9031 },
  { serviceCode: "NURSING-SEMI_PRIVATE",serviceName: "Nursing — Semi-Private (Daily)",    domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 350, isAutoCharged: true, unitLabel: "per day", displayOrder: 9032 },
  { serviceCode: "NURSING-PRIVATE",     serviceName: "Nursing — Private Room (Daily)",    domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 500, isAutoCharged: true, unitLabel: "per day", displayOrder: 9033 },
  { serviceCode: "NURSING-DELUXE",      serviceName: "Nursing — Deluxe Suite (Daily)",    domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 700, isAutoCharged: true, unitLabel: "per day", displayOrder: 9034 },
  { serviceCode: "NURSING-ICU",         serviceName: "Nursing — ICU (Daily)",             domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 1200, isAutoCharged: true, unitLabel: "per day", displayOrder: 9035 },
  { serviceCode: "NURSING-NICU",        serviceName: "Nursing — NICU (Daily)",            domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY", defaultPrice: 1500, isAutoCharged: true, unitLabel: "per day", displayOrder: 9036 },
  { serviceCode: "NURSING-DAYCARE",     serviceName: "Nursing — Day Care (Daily)",        domain: "DAYCARE", category: "NURSING", applicableTo: ["DAYCARE"], billingType: "PER_DAY", defaultPrice: 150, isAutoCharged: true, unitLabel: "per day", displayOrder: 9037 },

  // ── ER triage + OPD consultation + Doctor visits ─────────────────
  { serviceCode: "ER-TRIAGE",       serviceName: "Emergency Triage Charge",       domain: "EMERGENCY", category: "CONSULTATION", applicableTo: ["EMERGENCY"], billingType: "ONE_TIME",  defaultPrice: 500,  isAutoCharged: true, unitLabel: "one time", displayOrder: 9040, doctorOrderCategory: "Consultation" },
  { serviceCode: "OPD-CON",         serviceName: "OPD Consultation Fee",          domain: "OPD",       category: "CONSULTATION", applicableTo: ["OPD"],       billingType: "PER_VISIT", defaultPrice: 500, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9041, doctorOrderCategory: "Consultation" },
  { serviceCode: "CON-001",         serviceName: "Doctor Visit / Assessment",     domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD", "DAYCARE"], billingType: "PER_VISIT", defaultPrice: 400, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9042, doctorOrderCategory: "Consultation" },
  { serviceCode: "DOC-CONSULT",     serviceName: "Doctor Consultation",           domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD"],       billingType: "PER_VISIT", defaultPrice: 500, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9043, doctorOrderCategory: "Consultation" },
  { serviceCode: "DOC-MORN-ROUND",  serviceName: "Doctor Morning Round",          domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD"],       billingType: "PER_VISIT", defaultPrice: 400, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9044, doctorOrderCategory: "Consultation" },
  { serviceCode: "DOC-EVE-ROUND",   serviceName: "Doctor Evening Round",          domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD"],       billingType: "PER_VISIT", defaultPrice: 400, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9045, doctorOrderCategory: "Consultation" },
  { serviceCode: "DOC-NIGHT-ROUND", serviceName: "Doctor Night Round",            domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD"],       billingType: "PER_VISIT", defaultPrice: 500, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9046, doctorOrderCategory: "Consultation" },
  { serviceCode: "DOC-ICU-VISIT",   serviceName: "Doctor ICU Visit",              domain: "IPD",       category: "DOCTOR",       applicableTo: ["IPD"],       billingType: "PER_VISIT", defaultPrice: 800, isAutoCharged: true, unitLabel: "per visit", displayOrder: 9047, doctorOrderCategory: "Consultation" },

  // ── Engine-fired nursing codes ───────────────────────────────────
  { serviceCode: "NRS-001",  serviceName: "IV Cannulation",                domain: "IPD", category: "NURSING", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_PROCEDURE", defaultPrice: 150, isAutoCharged: true, unitLabel: "per procedure", displayOrder: 9050, doctorOrderCategory: "Nursing" },
  { serviceCode: "NRS-004",  serviceName: "Wound Dressing (Nurse)",        domain: "IPD", category: "NURSING", applicableTo: ["IPD", "DAYCARE", "OPD"], billingType: "PER_PROCEDURE", defaultPrice: 200, isAutoCharged: true, unitLabel: "per procedure", displayOrder: 9051, doctorOrderCategory: "Nursing" },
  { serviceCode: "NRS-005",  serviceName: "Skin Care / Pressure Care",     domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_PROCEDURE", defaultPrice: 100, isAutoCharged: true, unitLabel: "per procedure", displayOrder: 9052, doctorOrderCategory: "Nursing" },
  { serviceCode: "NRS-009",  serviceName: "Vitals Monitoring (Daily)",     domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_DAY",       defaultPrice: 100, isAutoCharged: true, unitLabel: "per day",       displayOrder: 9053, doctorOrderCategory: "Nursing" },
  { serviceCode: "NRS-BLD",  serviceName: "Blood Transfusion (Nurse)",     domain: "IPD", category: "NURSING", applicableTo: ["IPD"], billingType: "PER_UNIT",      defaultPrice: 500, isAutoCharged: false, unitLabel: "per unit",     displayOrder: 9054, doctorOrderCategory: "BloodTransfusion" },

  // ════════════════════════════════════════════════════════════════
  // R7hr-83 / Phase A5 — Doctor-Order starter rows for empty
  // categories. These give the Phase B autocomplete a starter list
  // for categories that the catalogue above doesn't already cover
  // (Diet, Oxygen, Physiotherapy, Activity, Nursing care, Consultation,
  // IV_Fluid). Upserts in seedServices() are $setOnInsert, so existing
  // rows with the same serviceCode are left untouched.
  // ════════════════════════════════════════════════════════════════

  // ── Diet ────────────────────────────────────────────────────────
  { serviceCode: "DIET-REG",   serviceName: "Regular Diet",   domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 150, isAutoCharged: false, unitLabel: "per day", displayOrder: 9100, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-DIAB",  serviceName: "Diabetic Diet",  domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 200, isAutoCharged: false, unitLabel: "per day", displayOrder: 9101, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-RENAL", serviceName: "Renal Diet",     domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 250, isAutoCharged: false, unitLabel: "per day", displayOrder: 9102, doctorOrderCategory: "Diet" },

  // ── Oxygen ──────────────────────────────────────────────────────
  { serviceCode: "OXY-NASAL", serviceName: "Nasal Cannula O2",          domain: "IPD", category: "NURSING", subCategory: "Oxygen", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_HOUR", defaultPrice: 50,   isAutoCharged: false, unitLabel: "per hour", displayOrder: 9110, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-MASK",  serviceName: "Face Mask O2",              domain: "IPD", category: "NURSING", subCategory: "Oxygen", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_HOUR", defaultPrice: 80,   isAutoCharged: false, unitLabel: "per hour", displayOrder: 9111, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-HFNC",  serviceName: "HFNC (High-Flow Nasal Cannula)", domain: "IPD", category: "ICU", subCategory: "Oxygen", applicableTo: ["IPD", "EMERGENCY"], billingType: "PER_HOUR", defaultPrice: 500, isAutoCharged: false, unitLabel: "per hour", displayOrder: 9112, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-VENT",  serviceName: "Mechanical Ventilation",    domain: "IPD", category: "ICU", subCategory: "Oxygen", applicableTo: ["IPD", "EMERGENCY"], billingType: "PER_HOUR", defaultPrice: 1500, isAutoCharged: false, unitLabel: "per hour", displayOrder: 9113, doctorOrderCategory: "Oxygen" },

  // ── Physiotherapy ───────────────────────────────────────────────
  { serviceCode: "PHYSIO-CHEST", serviceName: "Chest Physiotherapy",       domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 200, isAutoCharged: false, unitLabel: "per session", displayOrder: 9120, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-MOB",   serviceName: "Mobilization Physiotherapy", domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 250, isAutoCharged: false, unitLabel: "per session", displayOrder: 9121, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-RESP",  serviceName: "Respiratory Physiotherapy",  domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 300, isAutoCharged: false, unitLabel: "per session", displayOrder: 9122, doctorOrderCategory: "Physiotherapy" },

  // ── Activity ────────────────────────────────────────────────────
  { serviceCode: "ACT-AMB", serviceName: "Ambulation Assistance",       domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 100, isAutoCharged: false, unitLabel: "per session", displayOrder: 9130, doctorOrderCategory: "Activity" },
  { serviceCode: "ACT-PSV", serviceName: "Passive Range-of-Motion (ROM)", domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 150, isAutoCharged: false, unitLabel: "per session", displayOrder: 9131, doctorOrderCategory: "Activity" },

  // ── Nursing care ────────────────────────────────────────────────
  { serviceCode: "NURS-WOUND",     serviceName: "Wound Dressing (Nursing)", domain: "IPD", category: "NURSING", subCategory: "Bedside Care",  applicableTo: ["IPD", "DAYCARE", "OPD"], billingType: "PER_PROCEDURE", defaultPrice: 100, isAutoCharged: false, unitLabel: "per episode", displayOrder: 9140, doctorOrderCategory: "Nursing" },
  { serviceCode: "NURS-VITALS-Q1H", serviceName: "Hourly Vitals Monitoring", domain: "IPD", category: "NURSING", subCategory: "Monitoring",   applicableTo: ["IPD"],          billingType: "PER_DAY",     defaultPrice: 50,  isAutoCharged: false, unitLabel: "per day",     displayOrder: 9141, doctorOrderCategory: "Nursing" },
  { serviceCode: "NURS-IV-CARE",   serviceName: "IV Site Care",             domain: "IPD", category: "NURSING", subCategory: "Bedside Care", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY",    defaultPrice: 50,  isAutoCharged: false, unitLabel: "per day",     displayOrder: 9142, doctorOrderCategory: "Nursing" },

  // ── Consultation (engine-side starters) ─────────────────────────
  { serviceCode: "CON-EMERG",    serviceName: "Emergency Consultation", domain: "EMERGENCY", category: "CONSULTATION", subCategory: "Consultation", applicableTo: ["EMERGENCY"],         billingType: "PER_VISIT", defaultPrice: 500, isAutoCharged: false, unitLabel: "per visit", displayOrder: 9150, doctorOrderCategory: "Consultation" },
  { serviceCode: "CON-FOLLOWUP", serviceName: "Follow-up Consultation", domain: "OPD",       category: "CONSULTATION", subCategory: "Consultation", applicableTo: ["OPD", "IPD"],         billingType: "PER_VISIT", defaultPrice: 300, isAutoCharged: false, unitLabel: "per visit", displayOrder: 9151, doctorOrderCategory: "Consultation" },

  // ── IV Fluid ────────────────────────────────────────────────────
  { serviceCode: "IVF-NS",  serviceName: "Normal Saline 500ml",            domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 80,  isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9160, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-RL",  serviceName: "Ringer Lactate 500ml",           domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 90,  isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9161, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-DNS", serviceName: "Dextrose Normal Saline 500ml",   domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 100, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9162, doctorOrderCategory: "IV_Fluid" },

  // ════════════════════════════════════════════════════════════════
  // R7hr-83 / Phase B top-up — thicken under-populated doctorOrder
  // categories so Phase B autocomplete returns useful results.
  // Phase A backfill left these thin: Physiotherapy=1, Activity=0,
  // Diet=8, Oxygen=6, IV_Fluid=2. These rows top each up to >=5 new
  // entries. Upserts in seedServices() are $setOnInsert keyed on
  // serviceCode → idempotent and safe to re-run.
  // ════════════════════════════════════════════════════════════════

  // ── Physiotherapy (top-up) ──────────────────────────────────────
  { serviceCode: "PHYSIO-CHEST-PT", serviceName: "Chest Physiotherapy",       domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 300, isAutoCharged: false, unitLabel: "per session", displayOrder: 9170, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-PASS-ROM", serviceName: "Passive Range of Motion",   domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 200, isAutoCharged: false, unitLabel: "per session", displayOrder: 9171, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-AMBUL",    serviceName: "Assisted Ambulation",       domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 250, isAutoCharged: false, unitLabel: "per session", displayOrder: 9172, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-POST-OP",  serviceName: "Post-Op Mobilisation",      domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 400, isAutoCharged: false, unitLabel: "per session", displayOrder: 9173, doctorOrderCategory: "Physiotherapy" },
  { serviceCode: "PHYSIO-RESP-EX",  serviceName: "Respiratory Exercises",     domain: "IPD", category: "PROCEDURE", subCategory: "Physiotherapy", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_SESSION", defaultPrice: 250, isAutoCharged: false, unitLabel: "per session", displayOrder: 9174, doctorOrderCategory: "Physiotherapy" },

  // ── Activity (top-up) ───────────────────────────────────────────
  { serviceCode: "ACT-BED-REST",    serviceName: "Strict Bed Rest",           domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0, isAutoCharged: false, unitLabel: "per day", displayOrder: 9180, doctorOrderCategory: "Activity" },
  { serviceCode: "ACT-CHAIR",       serviceName: "Chair as Tolerated",        domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0, isAutoCharged: false, unitLabel: "per day", displayOrder: 9181, doctorOrderCategory: "Activity" },
  { serviceCode: "ACT-AMBUL-ASSIS", serviceName: "Ambulate with Assistance",  domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0, isAutoCharged: false, unitLabel: "per day", displayOrder: 9182, doctorOrderCategory: "Activity" },
  { serviceCode: "ACT-AMBUL-FREE",  serviceName: "Ambulate Ad Lib",           domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0, isAutoCharged: false, unitLabel: "per day", displayOrder: 9183, doctorOrderCategory: "Activity" },
  { serviceCode: "ACT-NO-LIFT",     serviceName: "No Lifting > 5 kg",         domain: "IPD", category: "NURSING", subCategory: "Activity", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0, isAutoCharged: false, unitLabel: "per day", displayOrder: 9184, doctorOrderCategory: "Activity" },

  // ── IV Fluid (top-up) ───────────────────────────────────────────
  { serviceCode: "IVF-NS-500",     serviceName: "Normal Saline 500 ml",        domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 120, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9190, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-NS-1000",    serviceName: "Normal Saline 1000 ml",       domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 180, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9191, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-DNS-500",    serviceName: "DNS 500 ml",                  domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 130, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9192, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-RL-500",     serviceName: "Ringer Lactate 500 ml",       domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 140, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9193, doctorOrderCategory: "IV_Fluid" },
  { serviceCode: "IVF-DEXT-5-500", serviceName: "Dextrose 5% 500 ml",          domain: "IPD", category: "PROCEDURE", subCategory: "IV Fluid", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_UNIT", defaultPrice: 130, isAutoCharged: false, unitLabel: "per bottle", displayOrder: 9194, doctorOrderCategory: "IV_Fluid" },

  // ── Diet (top-up) ───────────────────────────────────────────────
  { serviceCode: "DIET-NPO",      serviceName: "NPO / Nil Per Oral",  domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 0,   isAutoCharged: false, unitLabel: "per day", displayOrder: 9200, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-LIQUID",   serviceName: "Liquid Diet",         domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 150, isAutoCharged: false, unitLabel: "per day", displayOrder: 9201, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-SOFT",     serviceName: "Soft Diet",           domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 180, isAutoCharged: false, unitLabel: "per day", displayOrder: 9202, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-RT-FEED",  serviceName: "Ryle's Tube Feeding", domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 400, isAutoCharged: false, unitLabel: "per day", displayOrder: 9203, doctorOrderCategory: "Diet" },
  { serviceCode: "DIET-LOW-SALT", serviceName: "Low-Salt Diet",       domain: "IPD", category: "SUPPORT", subCategory: "Diet", applicableTo: ["IPD", "DAYCARE"], billingType: "PER_DAY", defaultPrice: 200, isAutoCharged: false, unitLabel: "per day", displayOrder: 9204, doctorOrderCategory: "Diet" },

  // ── Oxygen (top-up) ─────────────────────────────────────────────
  { serviceCode: "OXY-MASK-LFOW", serviceName: "Oxygen Mask Low Flow",            domain: "IPD", category: "NURSING", subCategory: "Oxygen", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_HOUR",    defaultPrice: 150,  isAutoCharged: false, unitLabel: "per hour",    displayOrder: 9210, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-MASK-NRB",  serviceName: "Non-Rebreather Mask",             domain: "IPD", category: "NURSING", subCategory: "Oxygen", applicableTo: ["IPD", "DAYCARE", "EMERGENCY"], billingType: "PER_HOUR",    defaultPrice: 400,  isAutoCharged: false, unitLabel: "per hour",    displayOrder: 9211, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-NIV",       serviceName: "NIV (BiPAP/CPAP) per session",    domain: "IPD", category: "ICU",     subCategory: "Oxygen", applicableTo: ["IPD", "EMERGENCY"],            billingType: "PER_SESSION", defaultPrice: 1500, isAutoCharged: false, unitLabel: "per session", displayOrder: 9212, doctorOrderCategory: "Oxygen" },
  { serviceCode: "OXY-VENTI",     serviceName: "Mechanical Ventilation per day",  domain: "IPD", category: "ICU",     subCategory: "Oxygen", applicableTo: ["IPD", "EMERGENCY"],            billingType: "PER_DAY",     defaultPrice: 6000, isAutoCharged: false, unitLabel: "per day",     displayOrder: 9213, doctorOrderCategory: "Oxygen" },
];

// ── Seed function ─────────────────────────────────────────────
// R7hr-12-S3: Refactored from sequential per-service findOne+create+create
// (≈3 round-trips × ~500 services = ~1500 RTTs, 30–60 s on a busy DB) to a
// bulkWrite-based upsert flow. Total round-trips collapse to ~4 regardless
// of catalogue size:
//   1. ServiceMaster.bulkWrite        — upsert all services in one shot
//   2. ServiceMaster.find             — fetch ids for the seeded serviceCodes
//   3. ServicePricing.find            — find which services already have CASH pricing (skip those)
//   4. ServicePricing.bulkWrite       — insert default CASH pricing for the rest
// Idempotent: re-running against a populated DB is a no-op (no duplicates).
async function seedServices() {
  let created = 0,
    skipped = 0,
    errors = 0;

  try {
    // ── Step 1: bulk-upsert ServiceMaster rows (single round-trip) ──
    // $setOnInsert ensures existing rows are NOT overwritten — preserves any
    // manual price/displayOrder edits made after the first seed.
    const masterOps = SERVICES.map((svc) => ({
      updateOne: {
        filter: { serviceCode: svc.serviceCode },
        update: { $setOnInsert: svc },
        upsert: true,
      },
    }));

    const masterResult = await ServiceMaster.bulkWrite(masterOps, {
      ordered: false,
    });

    // upsertedCount counts only newly-inserted rows; the rest were pre-existing.
    created = masterResult.upsertedCount || 0;
    skipped = SERVICES.length - created;

    // ── Step 2: fetch ids of all services in the catalogue (single round-trip) ──
    const codes = SERVICES.map((s) => s.serviceCode);
    const services = await ServiceMaster.find(
      { serviceCode: { $in: codes } },
      { _id: 1, serviceCode: 1 },
    ).lean();

    const codeToId = new Map(services.map((s) => [s.serviceCode, s._id]));

    // ── Step 3: figure out which services already have CASH pricing ──
    // We must not duplicate CASH rows for services seeded in a previous run.
    const allIds = services.map((s) => s._id);
    const existingPricings = await ServicePricing.find(
      { serviceId: { $in: allIds }, tariffType: "CASH" },
      { serviceId: 1 },
    ).lean();
    const haveCash = new Set(
      existingPricings.map((p) => String(p.serviceId)),
    );

    // ── Step 4: bulk-insert missing default CASH pricing rows ──
    // We bypass the pre-save hook by computing finalPrice inline (= price for
    // discount=0). insertOne is fine here because the haveCash filter
    // guarantees uniqueness on (serviceId, tariffType=CASH).
    const pricingOps = [];
    for (const svc of SERVICES) {
      const sid = codeToId.get(svc.serviceCode);
      if (!sid) continue;
      if (haveCash.has(String(sid))) continue;
      pricingOps.push({
        insertOne: {
          document: {
            serviceId: sid,
            tariffType: "CASH",
            price: svc.defaultPrice,
            discount: 0,
            finalPrice: svc.defaultPrice,
          },
        },
      });
    }

    if (pricingOps.length > 0) {
      await ServicePricing.bulkWrite(pricingOps, { ordered: false });
    }
  } catch (e) {
    console.error("Seed error (bulk):", e.message);
    errors++;
  }

  return { created, skipped, errors, total: SERVICES.length };
}

module.exports = { seedServices, SERVICES };
