const mongoose = require("mongoose");

const doctorSchema = new mongoose.Schema({

      Name:String,
      Age:Number,
      Gender:String,
      Contact:Number,
      Date:String,
      UHID:String,
      Email:String,
      fathername: String,
      Provisional_diagnosis1: String,
      IPNO: Number,
      consultant_incharge: Number,
      Presenting_complaints_Duration: String,
      History_of_Any_Allergy: String,
      Current_Medication: String,
      Past_history_surgical_proceduresdress: String,
      Birth_History_Mile_Stone: String,
      Family_History_Person_History: String,
      Level_of_consciousness: String,
      Nutritional_status: String,
      weight: Number,
      Temp: Number,
      BP: Number,
      Pulse: Number,
      Pallor: Number,
      Icterus: Number,
      Cyanosis: Number,
      Clibbing: Number,
      LymphNodes: Number,
      PedalEdema: String,
      Painscore: Number,
      Location: String,
      RespiratorySystem: String,
      Auscultation_Breath_Sounds: String,
      Auscultation_Added_Sounds: String,
      Location_of_Findings_Lungs: String,
      Location_of_Findings_Zone: String,
      Percussion_Note: String,
      Trachea_Position: String,
      Abdomen: String,
      Tenderness: String,
      Location_of_Tenderness: String,
      Organomegaly: Array,
      Bowel_Sounds: String,
      Ascites: String,
      Cardiovascular_System: String,
      Heart_Rhythm: String,
      Heart_Sounds_Added: String,
      Murmur_Timing: String,
      Murmur_Location: String,
      Murmur_Radiation: String,
      Peripheral_Edema: String,
      Jugular_Venous_Pressure: String,
      PA: String,
      Central_Nervous_System: String,
      Consciousness_Level: String,
      Motor_System_Focal_Deficit: String,
      Motor_System_Affected_Side: String,
      Tone: String,
      Reflexes_Deep_Tendon_Reflexes: String,
      Reflexes_Plantar_Reflex_Babinski: String,
      Reflexes_Side: String,
      Cranial_Nerves: String,
      Speech: String,
      Provisional_diagnosis: String,
      Treatment: String,
      Possible_risk: String,
      Training: String,
      Restraints: String,
      Investigation: String,
      Treatment_input: String,
      Diet: String,
       Hemiparesis:String,
      Hemiplegia:String,
      Paraparesis:String,
      Paraplegia:String,
      Quadriparesis:String,
      Quadriplegia:String,
});
module.exports = mongoose.model("Emergency_doctor", doctorSchema);




