// Backend/services/Pharmacy/pvpiSubmitter.js
//
// R7bm-F7 — PvPI (Pharmacovigilance Programme of India) Adverse Drug
// Reaction submission service. Originally a no-op stub (R7bh-F5); this
// revision tries the real CDSCO/IPC eForm endpoint when configured,
// falls back to the legacy log-only mode when not, and adds:
//
//   1. Configurable endpoint:
//        - PVPI_ENDPOINT_URL  (e.g. https://primaryreporting.who-umc.org/
//          api/individual-case-reports). The exact path is owned by
//          CDSCO/IPC; treat the URL as deployment-managed config and
//          override per environment. Leave unset to fall back to the
//          legacy stub behaviour without breaking the audit chain.
//        - PVPI_AUTH_TOKEN    (Bearer token issued by IPC after
//          hospital registration).
//        - PVPI_TIMEOUT_MS    (default 15s)
//
//   2. Retry-on-5xx (esp. 503) with exponential back-off so a brief
//      outage doesn't mark the ADR row as PVPI_FILED with a null
//      reference (which previously poisoned the audit trail). Retries
//      are bounded so a long outage still surfaces as a hard failure
//      the operator can replay manually.
//
//   3. Acknowledgement parsing: pulls the IPC-issued reference id out
//      of the response (`pvpiReference`, `caseId`, or `id`) and
//      surfaces it back to the caller — the controller persists it
//      onto ADRReport.pvpiReferenceNumber.
//
// Real Vigiflow API integration still requires CDSCO/IPC authority
// registration; once granted, set PVPI_ENDPOINT_URL + PVPI_AUTH_TOKEN
// via the deployment secret store and traffic switches automatically.
//
// TODO(R7bm-F7-PVPI): confirm the canonical CDSCO/IPC ingestion URL
// once the portal contract is signed. Two candidates today:
//   - https://primaryreporting.who-umc.org/ (WHO-UMC VigiFlow gateway)
//   - https://ipc.gov.in/PvPI/                (national portal)
// Keeping the env var so we can flip without a code change.

"use strict";

const https = require("https");
const http  = require("http");
const { URL } = require("url");

const DEFAULT_TIMEOUT_MS = Number(process.env.PVPI_TIMEOUT_MS || 15000);
const MAX_RETRIES        = Number(process.env.PVPI_MAX_RETRIES || 3);
const BASE_BACKOFF_MS    = Number(process.env.PVPI_BACKOFF_MS  || 500);

function _sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * Native-https POST. Avoids pulling axios into the Backend package
 * because pvpi traffic is low-volume and the dependency tree is kept
 * deliberately small for the pharmacy service.
 */
function _postJson(urlStr, body, headers = {}, timeoutMs = DEFAULT_TIMEOUT_MS) {
  return new Promise((resolve, reject) => {
    let u;
    try { u = new URL(urlStr); }
    catch (e) { reject(Object.assign(new Error(`Invalid PVPI_ENDPOINT_URL: ${urlStr}`), { code: "BAD_URL" })); return; }

    const client = u.protocol === "http:" ? http : https;
    const payload = Buffer.from(JSON.stringify(body || {}), "utf8");
    const opts = {
      method: "POST",
      hostname: u.hostname,
      port: u.port || (u.protocol === "http:" ? 80 : 443),
      path: `${u.pathname || "/"}${u.search || ""}`,
      headers: {
        "Content-Type": "application/json",
        "Content-Length": payload.length,
        Accept: "application/json",
        ...headers,
      },
      timeout: timeoutMs,
    };
    const req = client.request(opts, (res) => {
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => {
        const raw = Buffer.concat(chunks).toString("utf8");
        let parsed = null;
        try { parsed = raw ? JSON.parse(raw) : null; } catch (_) { parsed = null; }
        resolve({ statusCode: res.statusCode || 0, body: parsed, raw });
      });
    });
    req.on("timeout", () => {
      req.destroy(Object.assign(new Error("PVPI request timed out"), { code: "ETIMEDOUT" }));
    });
    req.on("error", (e) => reject(e));
    req.write(payload);
    req.end();
  });
}

function _extractReference(body) {
  if (!body || typeof body !== "object") return null;
  return (
    body.pvpiReference ||
    body.caseId ||
    body.caseReference ||
    body.reference ||
    body.id ||
    body.acknowledgementId ||
    null
  );
}

/**
 * Submit an ADR payload to the configured PvPI endpoint.
 *
 * @param {object} payload — generated by adrReportService.generatePvPIForm1
 * @returns {Promise<{success:boolean,queuedAt:Date,pvpiReference:?string,transport:string,statusCode?:number,attempts:number,errorMessage?:string}>}
 */
exports.send = async function send(payload) {
  const endpoint = process.env.PVPI_ENDPOINT_URL || "";
  const token    = process.env.PVPI_AUTH_TOKEN   || "";
  const now      = new Date();

  // Audit log entry regardless of transport — keeps the chain intact
  // even when the real endpoint isn't configured.
  // eslint-disable-next-line no-console
  console.log("[PvPI] submitting ADR:", JSON.stringify({
    severity: payload?.reaction?.severity,
    drug: payload?.drug?.name,
    patientUHID: payload?.patient?.UHID,
    reportedAt: payload?.reportedAt,
    transport: endpoint ? "http" : "stub",
  }));

  if (!endpoint) {
    // Stub mode — keep callers working until CDSCO credentials land.
    return {
      success: true,
      queuedAt: now,
      pvpiReference: null,
      transport: "stub",
      attempts: 0,
    };
  }

  const headers = token ? { Authorization: `Bearer ${token}` } : {};
  let lastErr = null;
  let lastStatus = 0;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const res = await _postJson(endpoint, payload, headers);
      lastStatus = res.statusCode;
      // 2xx — accepted
      if (res.statusCode >= 200 && res.statusCode < 300) {
        return {
          success: true,
          queuedAt: now,
          pvpiReference: _extractReference(res.body) || null,
          transport: "http",
          statusCode: res.statusCode,
          attempts: attempt,
        };
      }
      // Retry only on transient 5xx (esp. 503 Service Unavailable);
      // 4xx is a contract bug — fail fast without retry.
      if (res.statusCode >= 500 && res.statusCode < 600 && attempt < MAX_RETRIES) {
        const wait = BASE_BACKOFF_MS * Math.pow(2, attempt - 1);
        // eslint-disable-next-line no-console
        console.warn(`[PvPI] ${res.statusCode} on attempt ${attempt}, retrying in ${wait}ms`);
        await _sleep(wait);
        continue;
      }
      // Non-retryable: surface the error to the caller.
      lastErr = new Error(`PvPI rejected with status ${res.statusCode}: ${res.raw?.slice(0, 200) || ""}`);
      lastErr.statusCode = res.statusCode;
      break;
    } catch (e) {
      lastErr = e;
      // Network-level error — retry with backoff up to MAX_RETRIES.
      if (attempt < MAX_RETRIES) {
        const wait = BASE_BACKOFF_MS * Math.pow(2, attempt - 1);
        // eslint-disable-next-line no-console
        console.warn(`[PvPI] transport error on attempt ${attempt} (${e.code || e.message}), retrying in ${wait}ms`);
        await _sleep(wait);
        continue;
      }
      break;
    }
  }
  // All retries exhausted — return a failure shape the caller can persist.
  return {
    success: false,
    queuedAt: now,
    pvpiReference: null,
    transport: "http",
    statusCode: lastStatus || null,
    attempts: MAX_RETRIES,
    errorMessage: lastErr?.message || "Unknown PvPI submission error",
  };
};
