/**
 * FireDrillModel.js  (R7bf-G / A5-CRIT-7 / NABH FMS.4)
 *
 * Fire-drill / emergency-code register. NABH FMS.4 mandates periodic
 * (quarterly at minimum) drills for fire, evacuation, and the colour-
 * coded emergency response codes (Code Red = fire, Code Blue = arrest,
 * etc.) with documented observations, deficiencies, corrective actions,
 * and the next scheduled drill date.
 *
 * Pre-R7bf there was no register. Drills happened (or didn't) but no
 * audit-grade artefact tied them back to the facility manager.
 *
 * Drill numbers are auto-generated via Counter('FDR') — gap-less, IT-
 * Rule-46-friendly.
 */
const mongoose = require("mongoose");
const { Schema } = mongoose;

const FireDrillSchema = new Schema(
  {
    // Auto-generated by service via utils/counter ("FDR").
    drillNumber: { type: String, required: true, unique: true, index: true },

    // ── Schedule + actual ────────────────────────────────────
    scheduledDate: { type: Date, required: true, index: true },
    actualDate:    { type: Date, default: null },

    type: {
      type: String,
      enum: ["FIRE", "EARTHQUAKE", "BOMB_THREAT", "EVACUATION", "CODE_RED", "CODE_BLUE", "OTHER"],
      required: true,
      index: true,
    },

    // Area covered: ward, building, full-hospital, etc.
    area: { type: String, default: "" },

    // ── Conduct ──────────────────────────────────────────────
    conductedBy:     { type: Schema.Types.ObjectId, ref: "User", default: null },
    conductedByName: { type: String, default: "" },
    participantCount: { type: Number, default: 0, min: 0 },
    durationMinutes:  { type: Number, default: 0, min: 0 },

    // ── Outcome ──────────────────────────────────────────────
    observations:        { type: String, default: "" },
    deficienciesFound:   [{ type: String, trim: true }],
    correctiveActions:   [{ type: String, trim: true }],

    // ── Next drill ───────────────────────────────────────────
    // Used by the UI to flag overdue drills.
    nextDrillDue: { type: Date, default: null, index: true },

    status: {
      type: String,
      // R7bh-F6 / R7bg CRIT-A: OVERDUE added so the fire-drill-overdue
      // cron (Backend/services/Compliance/fireDrillOverdueCron.js) can
      // flag SCHEDULED drills past their nextDrillDue / scheduledDate
      // without losing the drill row entirely.
      enum: ["SCHEDULED", "COMPLETED", "CANCELLED", "OVERDUE"],
      default: "SCHEDULED",
      index: true,
    },

    notes:      { type: String, default: "" },
    hospitalId: { type: Schema.Types.ObjectId, ref: "Hospital", default: null },
  },
  { timestamps: true, collection: "fire_drills" },
);

FireDrillSchema.index({ status: 1, scheduledDate: -1 });
FireDrillSchema.index({ type: 1, scheduledDate: -1 });

module.exports =
  mongoose.models.FireDrill || mongoose.model("FireDrill", FireDrillSchema);
