/**
 * GrievanceModel.js  (R7bf-G / A5-CRIT-5 / NABH PRE.6)
 *
 * Patient grievance / complaint ledger. NABH PRE.6 mandates a structured
 * grievance redressal mechanism with SLA tracking, escalation matrix,
 * and resolution audit. Pre-R7bf no register existed — complaints lived
 * in the receptionist's notebook (and sometimes only in the patient's
 * memory).
 *
 * Lifecycle: OPEN → IN_PROGRESS | ESCALATED → RESOLVED → CLOSED
 *
 * Ticket numbers are auto-generated via Counter('GRV') so they stay
 * gap-less and audit-friendly.
 */
const mongoose = require("mongoose");
const { Schema } = mongoose;

const GrievanceAuditSchema = new Schema(
  {
    _id:      false,
    action:   {
      type: String,
      enum: ["CREATED", "ASSIGNED", "STATUS_CHANGED", "ESCALATED", "RESOLVED", "CLOSED", "NOTE"],
      required: true,
    },
    at:       { type: Date, default: Date.now },
    byName:   { type: String, default: "" },
    byRole:   { type: String, default: "" },
    byUserId: { type: Schema.Types.ObjectId, ref: "User", default: null },
    fromStatus: { type: String, default: "" },
    toStatus:   { type: String, default: "" },
    reason:   { type: String, default: "" },
  },
);

const GrievanceSchema = new Schema(
  {
    // Auto-generated by service via utils/counter ("GRV").
    ticketNumber: { type: String, required: true, unique: true, index: true },

    // ── Patient / complainant ─────────────────────────────────
    // UHID is optional because non-patient complainants (visitor,
    // vendor) are allowed too.
    patientUHID:        { type: String, trim: true, uppercase: true, default: "", index: true },
    complainantName:    { type: String, trim: true, required: true },
    complainantContact: { type: String, trim: true, default: "" },
    complainantType:    {
      type: String,
      enum: ["PATIENT", "RELATIVE", "VISITOR", "VENDOR", "STAFF", "OTHER"],
      default: "PATIENT",
    },

    // ── Complaint ─────────────────────────────────────────────
    category: {
      type: String,
      enum: ["CLINICAL", "BILLING", "BEHAVIOUR", "FOOD", "CLEANLINESS", "OTHER"],
      required: true,
      index: true,
    },
    description: { type: String, required: true, trim: true },

    raisedAt: { type: Date, default: Date.now, index: true },

    // ── Assignment ────────────────────────────────────────────
    assignedTo:     { type: Schema.Types.ObjectId, ref: "User", default: null },
    assignedToName: { type: String, default: "" },
    assignedAt:     { type: Date, default: null },

    // ── SLA ───────────────────────────────────────────────────
    slaHours: { type: Number, default: 48, min: 1 },

    // ── State ─────────────────────────────────────────────────
    status: {
      type: String,
      enum: ["OPEN", "IN_PROGRESS", "ESCALATED", "RESOLVED", "CLOSED"],
      default: "OPEN",
      index: true,
    },

    // ── Resolution ────────────────────────────────────────────
    resolvedAt:      { type: Date, default: null },
    resolvedBy:      { type: Schema.Types.ObjectId, ref: "User", default: null },
    resolvedByName:  { type: String, default: "" },
    resolutionNotes: { type: String, default: "" },

    // Patient satisfaction with the resolution (1-5). Captured when the
    // ticket is closed by the front-desk; null until then.
    satisfactionRating: { type: Number, default: null, min: 1, max: 5 },

    // Escalation
    escalatedAt:   { type: Date, default: null },
    escalatedTo:   { type: String, default: "" },
    escalatedToId: { type: Schema.Types.ObjectId, ref: "User", default: null },

    auditTrail: { type: [GrievanceAuditSchema], default: [] },

    hospitalId: { type: Schema.Types.ObjectId, ref: "Hospital", default: null },
  },
  { timestamps: true, collection: "grievances" },
);

GrievanceSchema.index({ status: 1, raisedAt: -1 });
GrievanceSchema.index({ category: 1, status: 1 });
GrievanceSchema.index({ patientUHID: 1, raisedAt: -1 });

module.exports =
  mongoose.models.Grievance || mongoose.model("Grievance", GrievanceSchema);
