/**
 * codeResponseService.js  (R7bj-F6 / NABH SEC-CRIT-1 / FMS.5 + COP.18)
 *
 * Service-layer for the unified emergency-code register. Workflow:
 *
 *   1. recordEvent(code, payload, actor)
 *        Activates a Code XXX. eventNumber auto-generated by Counter
 *        ("code_response:YYYY") via utils/counter.
 *
 *   2. addResponder(id, responder, actor)
 *        Each responder arriving on scene pushes a row. The first
 *        responder's arrivedAt seeds `arrivedFirstAt` + computes
 *        `arrivalDelaySec` (alertedAt → first responder).
 *
 *   3. resolveEvent(id, outcome, notes, actor)
 *        Closes the event. Sets resolvedAt + durationMinutes. Beyond
 *        this point the model is append-only except for `notes`.
 *
 *   4. list / stats — readers and MRT (mean response time) aggregation
 *        per code over a date window.
 */
const CodeResponseEvent = require("../../models/Compliance/CodeResponseEventModel");
const { nextSequence, formatId } = require("../../utils/counter");

function _err(code, message, status) {
  const e = new Error(message);
  e.code = code; e.status = status;
  return e;
}

function _istYear() {
  const tz = process.env.HOSPITAL_TZ || "Asia/Kolkata";
  return Number(new Intl.DateTimeFormat("en-CA", { timeZone: tz, year: "numeric" }).format(new Date()));
}

const VALID_CODES = ["BLUE", "RED", "PINK", "GREY", "YELLOW", "WHITE", "BROWN", "BLACK"];

async function recordEvent(code, payload = {}, actor = {}) {
  if (!code || !VALID_CODES.includes(String(code).toUpperCase())) {
    throw _err("ARG_INVALID", `code must be one of: ${VALID_CODES.join(",")}`, 400);
  }
  if (!payload.location) throw _err("ARG_MISSING", "location is required", 400);

  const year = _istYear();
  const seq = await nextSequence(`code_response:${year}`);
  const eventNumber = formatId(`CR-${year}`, seq, 5);  // CR-2026-00001

  const doc = await CodeResponseEvent.create({
    eventNumber,
    code:           String(code).toUpperCase(),
    location:       payload.location,
    bedNumber:      payload.bedNumber || "",
    alertedAt:      payload.alertedAt ? new Date(payload.alertedAt) : new Date(),
    alertedById:    actor._id || actor.id || null,
    alertedByName:  actor.fullName || actor.name || "",
    patientUHID:    payload.patientUHID ? String(payload.patientUHID).toUpperCase().trim() : "",
    patientName:    payload.patientName || "",
    responders:     [],
    notes:          payload.notes || "",
    hospitalId:     actor.hospitalId || payload.hospitalId || null,
  });
  return doc;
}

/**
 * Add a responder. Computes arrivedFirstAt / arrivalDelaySec on the
 * first push (idempotent — subsequent calls don't overwrite the first
 * responder's timestamp).
 */
async function addResponder(id, payload = {}, actor = {}) {
  const doc = await CodeResponseEvent.findById(id);
  if (!doc) throw _err("NOT_FOUND", "Code-response event not found", 404);
  if (doc.resolvedAt) throw _err("ALREADY_RESOLVED", "Cannot add responder to a resolved event", 409);

  const arrivedAt = payload.arrivedAt ? new Date(payload.arrivedAt) : new Date();
  doc.responders.push({
    byUserId: payload.byUserId || actor._id || actor.id || null,
    name:     payload.name || actor.fullName || actor.name || "",
    role:     payload.role || actor.role || "",
    arrivedAt,
  });

  // First-responder timing.
  if (!doc.arrivedFirstAt || arrivedAt < doc.arrivedFirstAt) {
    doc.arrivedFirstAt = arrivedAt;
    const alerted = new Date(doc.alertedAt).getTime();
    if (Number.isFinite(alerted)) {
      doc.arrivalDelaySec = Math.max(0, Math.round((arrivedAt.getTime() - alerted) / 1000));
    }
  }
  await doc.save();
  return doc;
}

async function resolveEvent(id, payload = {}, actor = {}) {
  if (!payload.outcome) throw _err("ARG_MISSING", "outcome is required", 400);
  const validOutcomes = ["RESOLVED", "ESCALATED", "FALSE_ALARM", "PRONOUNCED_DEAD", "TRANSFERRED"];
  if (!validOutcomes.includes(payload.outcome)) {
    throw _err("ARG_INVALID", `outcome must be one of: ${validOutcomes.join(",")}`, 400);
  }
  const now = new Date();
  const doc = await CodeResponseEvent.findOne({ _id: id, resolvedAt: null });
  if (!doc) {
    const existing = await CodeResponseEvent.findById(id).lean();
    if (!existing) throw _err("NOT_FOUND", "Code-response event not found", 404);
    throw _err("ALREADY_RESOLVED", "Event is already resolved", 409);
  }
  const alerted = new Date(doc.alertedAt).getTime();
  const durationMinutes = Number.isFinite(alerted)
    ? Math.max(0, Math.round((now.getTime() - alerted) / 60000))
    : null;

  doc.resolvedAt      = now;
  doc.durationMinutes = durationMinutes;
  doc.outcome         = payload.outcome;
  if (payload.notes) doc.notes = payload.notes;
  if (Number.isFinite(payload.evacuationCount)) doc.evacuationCount = payload.evacuationCount;
  if (payload.linkedMortuaryId) doc.linkedMortuaryId = payload.linkedMortuaryId;
  if (payload.linkedIncidentId) doc.linkedIncidentId = payload.linkedIncidentId;

  await doc.save();
  return doc;
}

async function getById(id) {
  if (!id) return null;
  return CodeResponseEvent.findById(id).lean();
}

async function list({ code, from, to, outcome, uhid, limit = 100 } = {}) {
  const q = {};
  if (code)    q.code = String(code).toUpperCase();
  if (outcome) q.outcome = outcome;
  if (uhid)    q.patientUHID = String(uhid).toUpperCase().trim();
  if (from || to) {
    q.alertedAt = {};
    if (from) q.alertedAt.$gte = new Date(from);
    if (to)   q.alertedAt.$lte = new Date(to);
  }
  return CodeResponseEvent.find(q)
    .sort({ alertedAt: -1 })
    .limit(Math.min(500, Math.max(1, Number(limit) || 100)))
    .lean();
}

/**
 * Mean Response Time (MRT) per code over a date window. Returns rows
 * shaped { code, eventCount, mrtSec, avgDurationMin, falseAlarmCount }.
 * MRT uses arrivalDelaySec across events that have a first responder
 * recorded; events with no responder are excluded from the MRT but
 * still counted in eventCount + falseAlarmCount.
 */
async function stats({ from, to } = {}) {
  const match = {};
  if (from || to) {
    match.alertedAt = {};
    if (from) match.alertedAt.$gte = new Date(from);
    if (to)   match.alertedAt.$lte = new Date(to);
  }
  const rows = await CodeResponseEvent.aggregate([
    { $match: match },
    {
      $group: {
        _id: "$code",
        eventCount: { $sum: 1 },
        mrtSec: {
          $avg: {
            $cond: [{ $ne: ["$arrivalDelaySec", null] }, "$arrivalDelaySec", "$$REMOVE"],
          },
        },
        avgDurationMin: {
          $avg: {
            $cond: [{ $ne: ["$durationMinutes", null] }, "$durationMinutes", "$$REMOVE"],
          },
        },
        falseAlarmCount: {
          $sum: { $cond: [{ $eq: ["$outcome", "FALSE_ALARM"] }, 1, 0] },
        },
      },
    },
    { $project: { _id: 0, code: "$_id", eventCount: 1, mrtSec: 1, avgDurationMin: 1, falseAlarmCount: 1 } },
    { $sort: { code: 1 } },
  ]);
  return rows;
}

module.exports = { recordEvent, addResponder, resolveEvent, getById, list, stats };
